### ISSUE TITLE
Compatibility with gradle 7.6

### ISSUE THREAD

**Issue by llDavidll** [google/truth#1056]
Hi,

I think there is an issue when using the truth library with gradle 7.6, at least with my current project configuration.
When the tests are ok, everything runs great. But if a test fails, I get an error instead of the usual truth error display.

I attached a zip with a really simple project using kotlin, gradle and truth. There is only one test (is 1 equals to 2 ?)
[truthandgradle.zip](https://github.com/google/truth/files/10269332/truthandgradle.zip)

- Run tests : Gradle Tasks -> verification -> allTests
The default gradle version of the project being 7.5.1, it fails as it should : 
expected: 2
but was : 1
	at app//com.example.truthandgradle.TestClass.test(ExampleUnitTest.kt:12)

- Change gradle version to 7.6 in gradle -> wrapper -> gradle-wrapper.properties
- Sync project
- Run tests : Gradle Tasks -> verification -> allTests
This time I get this error : 
Receiver class org.jetbrains.kotlin.gradle.targets.jvm.tasks.KotlinJvmTest$Executor$execute$1 does not define or inherit an implementation of the resolved method 'abstract void failure(java.lang.Object, org.gradle.api.tasks.testing.TestFailure)' of interface org.gradle.api.internal.tasks.testing.TestResultProcessor.

**Comment by JakeWharton** [comment]
Roll back to Gradle 7.5 or upgrade to Kotlin 1.8.0-RC2: https://youtrack.jetbrains.com/issue/KT-55172.

This is not a Truth issue.

**Comment by llDavidll** [comment]
Oh, I should have tried writing a test without truth, it didn't even cross my mind... Thank you for the quick answer.
