### ISSUE TITLE
404 on links from /usage

### ISSUE THREAD

**Issue by haxney** [google/truth#128]
There are a couple of broken links on http://google.github.io/truth/usage:
- Under the heading "Super basics", the link "More examples are here" goes to http://google.github.io/detail, which gives a 404
- Under "More Comprehensive Examples", the link "can be found in the Example section" goes to http://google.github.io/detail as well.
- Under "Extensibility", the link "Extending Truth" goes to http://google.github.io/extension, which gives a 404

**Comment by dimo414** [comment]
Also, on http://google.github.io/truth/ there's a reference to `http://search.maven.org/remotecontent?filepath=org/truth0/truth/0.26/truth-0.26.jar` which fails.

The `README.md` file also references release 0.25 as being the latest release.

**Comment by dimo414** [comment]
Seems like all these broken links have been removed, is this bug resolved?

**Comment by cgruber** [comment]
I think so.
