### ISSUE TITLE
The code font for the website is difficult to read

### ISSUE THREAD

**Issue by andresdominguez** [google/truth#135]
The font is too small. The comments are gray on a gray background. Consider using better font + colors

Here is a good example: 

http://googlecloudplatform.github.io/gcloud-node/#/

**Comment by cpovirk** [comment]
We switched over to a Material theme in https://github.com/google/truth/commit/38f1eea74864015d26dd87a59ea0ed8b9a66de6a. Hopefully that has given us something well-tested for readability.
