### ISSUE TITLE
IteratingWrapperClassBuilder does not forward multiple arguments to correctly

### ISSUE THREAD

**Issue by dhomann** [google/truth#144]
Using thatEach with a custom SubjectFactory results in the compilation of a generated class, which forwards the proposition arguments to the original subject:

    Iterable<Foo> data = iterable(new Foo(2 + 3), new Foo(2 + 4));
    assert_().in(data).thatEach(FooSubject.FOO).matchesEither(new Foo(5), new Foo(6));

The generated code has a bug and the first argument Foo(5) will be passed to the original subject's method multiple times. All additional arguments will be dropped:

`Not true that <Foo(6)> matches one of <Foo(5)> <Foo(5)>`

In cases where the arguments have incompatible types, the generated code does not even compile.

**Comment by cpovirk** [comment]
Fixed by eliminating the feature. Sorry for leaving this hanging so long.

**Comment by cpovirk** [comment]
(My mistake: Apparently we did commit the fix after all: https://github.com/google/truth/commit/ad4e9459f802ee340d2ea38b6abce9fa0e47d7d2)
