### ISSUE TITLE
int vs long in error messages

### ISSUE THREAD

**Issue by sjamesr** [google/truth#151]
I'm sure this isn't a new issue but I couldn't find an existing report:

```
assertThat(ImmutableList.of(1L)).containsExactly(1);
```

Results in

```
java.lang.AssertionError: Not true that <[1]> contains exactly <[1]>. It is missing <[1]> and has unexpected items <[1]>
```

In the situation where the output would be ambiguous, it would be nice if Truth would disambiguate by adding the "L" suffix as necessary.

**Comment by cpovirk** [comment]
I believe that we now do this. (Certainly we do a bunch of things _like_ this; if we're missing something specific, please let us know.)
