### ISSUE TITLE
Subject.isIn(Iterable<?>) (and/or varargs)

### ISSUE THREAD

**Issue by cpovirk** [google/truth#164]
I just saw some code like this (caveat: It was automatically generated from a migration from an old `assertContains` method, but I think the point stands equally well under those circumstances):

`assertThat(ImmutableList.of(FOO, BAR, BAZ), contains(object.getValue());`

If this comes up much, it would be nice for users to be able to write:

`assertThat(object.getValue()).isIn(ImmutableList.of(FOO, BAR, BAZ));`

But perhaps that's more useful with constants:

`assertThat(promotion.getCountry()).isIn(SUPPORTED_COUNTRIES);`

And users who don't have a constant would probably prefer:

`assertThat(object.getValue()).isOneOf(FOO, BAR, BAZ)`

Needless to say, this would require further research and discussion.

**Comment by TastyPi** [comment]
I also have a use case for this method. `isEqualToAnyOf` is a bit verbose in my opinion, something like `isOneOf` or `isAnyOf` for the varargs version would be good (although I don't have strong feelings about the name). `isIn` or `isContainedIn` would be good names for the `Collection` version. `isContainedIn` matches the `Collection#contains`.

**Comment by PeteGillinGoogle** [comment]
I have a fix for this in flight.

**Comment by kluever** [comment]
For the record, we're going with the following API:
isIn(Iterable) / isNotIn(Iterable)
isAnyOf(first, second, rest...) / isNoneOf(first, second, rest...)
