### ISSUE TITLE
Some way of naming the actual value, maybe for cases in which there isn't a clear distinction between actual and expected?

### ISSUE THREAD

**Issue by cpovirk** [google/truth#175]
A comment from a pending CL to Guava, in which I write my own assertion:

```
  if (urlsFromLoader.size() != urlsFromClassPath.size()) {
    fail(String.format(
        "Number of URLs from system classloader (%s) and number of URLs from ClassPath (%s) "
            + "do not match",
        urlsFromLoader.size(), urlsFromClassPath.size()));
  }
```

> I could just do assertThat(urlsFromClassPath.size()).named("URLs from ClassPath for resource " + resource).isEqualTo(urlsFromLoader.size()), but I have reservations:
> 
> _snip other reservation_
> - I'm wondering how legitimate it is to say that the number of URLs from the ClassLoader is the "right" number. I'm not sure why -- I guess because it's computed, too, in a way complicated enough that it might be wrong? But that would still mean that it's "expected," just that we're uncertain. I guess that's why I want to give it a label, too -- to say that we expected the actual value to match the number from the ClassLoader, rather than "it should obviously be 3."

I'm not sure that I have a real point there, but it's at least possible that I have a scenario in which I really don't have a true "expected." Suppose that I have two pieces of code I want to keep in sync -- maybe two sets of constants in separate classes that need to match but can't for build-system reasons. It's a little weird to say that one is "expected" and the other "actual."

Do we really care? Probably not, especially since I have no idea how our API would accommodate this. But I'm filing the issue while it's on my mind. Maybe it will turn out to be important someday, and maybe someone will come up with an elegant solution. But I plan to forget about this entirely for a while :)

**Comment by dimo414** [comment]
Personally, I'd say the values provided by the ClassLoader are properly called "expected" - you're testing that your code generates the same result as what the ClassLoader returns, it doesn't really matter *how* it gets that result.

Now, it might make sense to (a) log more details about the ClassLoader's state (b) create separate tests that assert on the ClassLoader's behavior or (c) add additional sanity-check assertions before "expect"-ing the ClassLoader's output, but those options are all distinct from what we call it once we do decide to treat the ClassLoader's output as "expected".

**Comment by cpovirk** [comment]
I think you're right: It's just uncertainty about whether `ClassLoader` is doing what I expect. Maybe another way to look at it is this: If the test fails, I might change `ClassPath`, or I might change `ClassPathTest`. But I'm not likely to change `ClassLoader` :)

**Comment by cpovirk** [comment]
(I just came across a test that compared `a.equals(b)` and `a.compareTo(b) == 0`. Arguably neither of these is the clear "expected" or "actual"; we're just looking for _compatibility_ between the two. Not that I think that's enough reason to resurrect this proposal.)
