### ISSUE TITLE
What happened to Truth.ASSERT?

### ISSUE THREAD

**Issue by mfulton26** [google/truth#180]
I personally liked statically importing Truth.ASSERT (instead of `assert_()`) in version 0.25. Is there a reason that in version 0.26 Truth.ASSERT is now private? It looks like this was last changed in https://github.com/google/truth/commit/8b1cab0c50e23fd13a0b36df68c84fcd90de64e7 but I wasn't even aware that the TruthVerb Truth.ASSERT was deprecated. I find `assert_()` awkward to read and type while I find `ASSERT` easy to read and type as well as consistent because now I can use the same grammar whether I define a custom failure message or not. I love consistency. Can we please make Truth.ASSERT public again?

**Comment by lowasser** [comment]
I believe the expectation is that you'll be static importing assertThat and using it directly pretty much everywhere, or assertWithMessage, etc. rather than explicitly calling assert_().

**Comment by mfulton26** [comment]
I see, and there is an assertAbout as well. So should assert_() be public? If one should be public then they might as well both be... I'm just sharing my thoughts. However, now that I know how to use the different assertions without using assert_() I'm not to concerned about it. Thank you.

**Comment by vdhananjay** [comment]
I vote for Assert.Truth and leave the rest to you guys.

**Comment by kluever** [comment]
+1 to what @lowasser said above.

re. assert_() being public: it can still be useful in case you are already static importing a method called assertThat (for instance, if you're mixing Hamcrest and Truth in the same file).
