### ISSUE TITLE
Figure out if DoubleSubject.isEqualTo is a legitimate method to call

### ISSUE THREAD

**Issue by cpovirk** [google/truth#187]
We mentioned this in (Google-internal, sorry) doc https://docs.google.com/document/d/1YfXxGR3-SZSa56cfnUXa2OnfE9VaJ6vlCJA4UYvgSoU/edit

But we don't seem to have resolved it.

I argue that it's useful for at least "isEqualTo(0.0)," since 0.0 is the "unset" value.

I also argue that it's sad to break symmetry in cases like this (a Dagger test):

    assertThat(component.s()).isEqualTo("sam");
    assertThat(component.i()).isEqualTo(1);
    assertThat(component.d()).isWithin(0).of(4.2d);
    assertThat(component.f()).isEqualTo(5.5f);
    assertThat(component.l()).isEqualTo(6L);

Of course, the tolerance is quite often justified: Whenever you're doing math, I'd worry about using an exact value. But I think there are enough tests that are basically like the above: Return "4.2" from one place, and check that you get "4.2" as an output. The input for that test:

    @Provides
    double d() {
      return 4.2d;
    }

(This will require a real API review doc, but I wanted to get my thoughts down here first. Perhaps others will have comments.)

**Comment by cpovirk** [comment]
New reason to support plain `isEqualTo`: It gives us more flexibility with error messages:

    assertThat([1.0, 2.0, 3.0]).isEqualTo([1.0, 99.0, 2.0, 3.0])

If we know that we're using exact equality, we know that we have a transitive operation, so we can behave like `containsExactly(...).inOrder()` and report that the two are identical except that the subject "does not contain 99.0."

If we're doing fuzzy equality, we are unlikely to be able to do anything sane except to say that the sizes are different and that the elements and indexes 1 and 2 differ.

(It's not 100% clear that this is an improvement, but I wanted to get it down while it was on my mind.)

**Comment by cpovirk** [comment]
Using a tolerance gets weird for the "not equals" case:

    assertThat([1.0, 2.0, 3.0]).isNotWithin(0.1).of([1.0, 2.0, 3.0, 99.0])

Should that test pass, or should it throw IllegalArgumentException because the lengths differ?

I think that `isWithin`/`isNotWithin` may necessarily mean "pairwise comparison." If so, then maybe we should just blow up if the size doesn't match?

**Comment by PeteGillinGoogle** [comment]
On doubles and isEqualTo:
 - That method does exist, and does to the obvious thing (delegates to Double object equality). It is deprecated, on the grounds that most people don't want exact equality, but if isEqualTo is just sitting there then many people will just use it, and this encourages people to at least think about it.
 - I feel quite strongly that argument trumps the symmetry-breaking argument.
 - Inside Google, ~19% of uses of isWithin have a zero tolerance (according to my slightly crude search).
 - The javadoc for isWithin says you're welcome to use a zero tolerance and discusses when that might be appropriate. (At least, it does internally, I think maybe that hasn't made it into an open-source release yet.)
 - There have been suggestions that we should add isExactlyEqualTo as a synonym for isWithin(0.0). I would be open to that, but nobody has formally proposed it.
 - If we did add isExactlyEqualTo, we could make it give a different failure message.

**Comment by PeteGillinGoogle** [comment]
The same goes for double arrays and isEqualTo.

**Comment by PeteGillinGoogle** [comment]
On double arrays and isNotWithin and different length arrays:

First up, I agree that this is a bit of a weird situation.

The change to add this method is out for review (internally, I'll CC you, Chris). Kurt asked exactly this question. Here's a quote from my reply:

> What's the thinking? That when someone says that something should have values not within a tolerance of 1.0, 2.0, 3.0, they mean that it should have three values but that they shouldn't all be within tolerance of those values? Is that what you'd expect it to mean?

> It's really hard to predict what people really want from this method, since... absolutely nobody is using isNotEqualTo [for double arrays, inside Google].

> However, I think I'd argue that we should make isNotWithin diverge from isNotEqualTo as little as possible, and isNotEqualTo passes in this case.

> (Aside: If we do decide to throw in this case, is an IAE rather than failing the test correct even in that case? It seems to me that an IAE should mean that the test code is wrong, not that the code under test is wrong.)

To which Kurt gave an "SGTM".

If you want to present counter-arguments, can you chip in on that in-flight change? Thanks.

**Comment by cgruber** [comment]
@PeteGillinGoogle - do you want to bring this bug up to currency?  Just a note about where we're at, so far, and what we plan to have in for 1.0?

**Comment by PeteGillinGoogle** [comment]
Here are the haps:
- Single doubles:
  - assertThat(double).isWithin(1e-5).of(3.14159); is supported
  - assertThat(double).isNotWithin(1e-5).of(3.14159); is supported
  - assertThat(double).isEqualTo(3.14159); is supported but deprecated — use the above, with a zero tolerance if appropriate
  - assertThat(double).isNotEqualTo(3.14159); is supported but deprecated — use the above, with a zero tolerance if appropriate
- Double arrays:
  - assertThat(doubleArray).hasValuesWithin(1e-5).of(1.0, 3.14159, 2.71828); is supported *but* will be deprecated in a future version
  - assertThat(doubleArray).withTolerance(1e-5).containsExactly(1.0, 3.14159, 2.71828).inOrder(); is planned as a replacement for that
  - various other operations after withTolerance (any-order containsExactly, contains, containsAny, containsAll, etc.) are also planned (and are starting to appear at top-of-tree)
  - assertThat(doubleArray).hasNotValuesWithin(1e-5).of(1.0, 3.14159, 2.71828); is supported but deprecated at top-of-tree — it was never used inside Google and, as discussed above, there is no semantic which doesn't lead to confusion
  - assertThat(doubleArray).isEqualTo(new double[] {1.0, 3.14159, 2.71828}); is deprecated and throws an exception — use one of the above, using a zero tolerance if appropriate
  - assertThat(doubleArray).isNotEqualTo(new double[] {1.0, 3.14159, 2.71828}); is deprecated and throws an exception — if you really need this, use Double.asList and make an assertion on the resulting List<Double>
- Double Iterables:
  - assertThat(doubleIterable).containsExactly(1.0, 3.14159, 2.71828).inOrder() is supported, although be aware that this does exact f.p. equality
  - assertThat(doubleIterable).comparingElementsUsing(tolerance(1e-5)).containsExactly(1.0, 3.14159, 2.71828).inOrder() is planned as a tolerant version of that
  - various other operations after comparingElementsUsing (any-order containsExactly, contains, containsAny, containsAll, etc.) are also planned (and are starting to appear at top-of-tree)
  - assertThat(doubleIterable).isEqualTo(ImmutableList.of(1.0, 3.14159, 2.71828)) is supported, but using contains* methods, possibly also with comparingElementsUsing(tolerance(1e-5)), is preferred
  - assertThat(doubleIterable).isNotEqualTo(ImmutableList.of(1.0, 3.14159, 2.71828)) is supported, although be aware that this does exact f.p. equality

All the planned stuff *should* be ready for 1.0, and there *should* be much less API churn after that.

I'm also planning on adding something to the documentation pulling all of this together.

(FYI, all of the deprecated stuff is deleted in the Google-internal version, where we can be sure that all usages have been migrated.)

**Comment by cpovirk** [comment]
Pete left some arguments against this in #259. Thanks, Pete.

I will try to actually make my case in favor soon so that we can take this to an API Review and decide once and for all.

**Comment by PeteGillinGoogle** [comment]
Chris, I literally just added a proposal to the API review queue to add DoubleSubject.isExactlyEqualTo. I'm hoping this will keep everyone happy :-).

**Comment by PeteGillinGoogle** [comment]
(It doesn't completely address the symmetry argument you make in your first post on this issue, although it improves things. I believe that all the other points you make have been addressed since. The current & proposed APIs give the nice error messages you mention in your second post, and the weird hasValuesNotWithin is deprecated already.)

**Comment by cpovirk** [comment]
OK, then I guess I'd better get on with making that case :) Thanks again.

**Comment by cpovirk** [comment]
(I do agree that you've solved a number of the issues here.)

**Comment by cpovirk** [comment]
OK, here's my opinion. I've added it to our internal doc, but if anyone would like to add anything, please do, and we'll copy it to the internal doc for our discussion.


isWithin() is the right tool when you're doing math; isEqualTo is the right tool when you're not. We should encourage both.

First: What does this code say?

assertThat(getOpacity(0)).isWithin(0).of(0.4);

To me, the emphasis is, "I am performing some math, and it's important that the result be exact."

But in fact the previous line is:

setOpacity(0, 0.4);

There's no math here. Given that, I would prefer to see:

assertThat(getOpacity(0)).isEqualTo(0.4);

Now, this is partially about parallelism: I'm doing conceptually the same thing here with an int:

setHeight(0, 400);
assertThat(getHeight(0)).isEqualTo(400);

So why should my code look different in the double case?

But it's not just parallelism: It's that "isWithin" suggests "math is happening." (I'm trying to decide if I feel the same way, to a much, much lesser extent, about the proposed "isExactlyEqualTo.")

(Minor digression: I think that "is within zero of" is the kind of thing only a mathematician would say. More importantly, it's not necessarily obvious to users that "is within zero of" is even a valid thing to do.)

The bigger issue, though, is that isWithin() doesn't deliver on its promise: Using isWithin(0) probably breaks more tests that using isEqualTo(). The data: If I migrate every DoubleSubject.isEqualTo() call to isWithin(0), ~3% of migrated tests break.

Like these tests:

assertThat(getDeadline()).isEqualTo(NO_DEADLINE);
assertThat(actual.getProbability()).isEqualTo(expected.getProbability());
assertThat(model.getBudget()).isEqualTo(budget);

That last user has suppressed the deprecation warning. Here's what he'd need to do to avoid isEqualTo():

    @Test
    public void model(MyProto proto, Double budgetAmount) {
      // set up model...

      if (budgetAmount == null) {
        assertThat(model.getBudget()).isNull();
      } else if (budgetAmount == POSITIVE_INFINITY) {
        assertThat(model.getBudget()).isPositiveInfinity();
      } else if (budgetAmount == NEGATIVE_INFINITY) {
        assertThat(model.getBudget()).isNegativeInfinity();
      } else {
        assertThat(model.getBudget()).isWithin(0).of(budgetAmount);
      }
    }

OK, I'm exaggerating: This particular user needs to handle only the null case. But other tests fail because they're trying to compare the fields of an expected object and an actual object and they find some field is NaN or infinity. If you want to write a generalized test that those two objects match, you need to write something like the above.

Or you can use the proposed isExactlyEqualTo(). I hope I've at least made the case that we need that. And I can live with having isExactlyEqualTo() -- one that accepts a boxed Double (so that it can handle null) and duplicates the Number-handling logic of isEqualTo().

But then we're back to the question of why we'd steer users off isEqualTo() in the first place. I feel like we're going to a lot of effort to be prescriptive. And believe me, I'm generally a fan of being prescriptive :) Prescriptiveness can be worth it if we're saving users from subtle problems or even obvious but pervasive problems. But I have searched CLs for evidence of problems with no-tolerance comparisons and found nothing.

I'm sure that people occasionally have this problem when writing the code for the first time and very occasionally even when making a subsequent change. But how big a problem can this be if they don't even mention it in the CL description? Where are the rants? :)

If there were a significant problem here, I'd expect to hear about it: The Google depot's tests of double values are split 50-50 between exact and fuzzy.

Are we making the world better when we force users to think "Am I comparing objects that happen to be doubles?" when they're often not doing math?

Plus, we're not really "forcing" them: We're not proposing to make isEqualTo() throw UOE. It's still there, and it still works. (And I think it should: If it doesn't, we're outright breaking people to avoid a <<1%(?) chance of breaking them later.) So now we have *three* ways to compare doubles. And sure, two of them are the same. But again, why are we going to all this trouble? I really feel like I'm missing something.

If we want to write static analysis to suggest a tolerance for cases where someone is writing a "math-looking" result like "isEqualTo(0.562)," then OK. But I think deprecation is wrong.

**Comment by cpovirk** [comment]
We ended up deciding that it was legitimate in some cases: https://github.com/google/truth/commit/12f60591cd281f43ef9d20e53d00d59778d05fe0
