### ISSUE TITLE
Check whether iterator contains item matching predicate

### ISSUE THREAD

**Issue by jonas-l** [google/truth#188]
I found ```IteratingVerb``` only has ```thatEach``` while I would expect to also see ```thatAtLeastOne``` (best name I could come up right now) for testing existence of item in iterable matching the predicate.

Improvised test case:
``` Java
Iterable<String> data = Arrays.asList("foo", "bar");
assert_()
    .in(data)
    .thatAtLeastOne(BarSubject.BAR)
    .startsWith("f");
try {
  assert_()
      .in(data)
      .thatAtLeastOne(BarSubject.BAR)
      .startsWith("x");
  assert_().fail("Expected assertion to fail.");
} catch (AssertionError expected) {
  assertThat(expected).hasMessage("Not true that any of <[foo, bar]> starts with <x>");
}
```

**Comment by jonas-l** [comment]
Oops, it looks like there already was a ticket #178 asking for similar feature just different approach.

**Comment by cpovirk** [comment]
This is unfair of me for multiple reasons, but I'm going to close this out in favor of #206 to consolidate the discussion.
