### ISSUE TITLE
Name for named null reference ignored

### ISSUE THREAD

**Issue by dbarnett** [google/truth#189]
The custom name from `.named()` doesn't seem to appear anywhere in the error if the subject evaluates to null:
```java
assertThat((String) null).named("somename").isEqualTo("someval")
```
Error: `java.lang.AssertionError: Not true that null reference is equal to <"someval">`

This is what the error looks like if I use empty string instead of null:
```java
assertThat("").named("somename").isEqualTo("someval")
```
Error: `org.junit.ComparisonFailure: "somename": expected:<[someval]> but was:<[]>`

**Comment by dbarnett** [comment]
Possibly specific to StringSubject. For `(Object) null` instead of `(String) null`, I get: `java.lang.AssertionError: Not true that somename (<null>) is equal to <someval>`

**Comment by kluever** [comment]
This should be mirrored out shortly.
