### ISSUE TITLE
Remove type parameters from all collection subjects?

### ISSUE THREAD

**Issue by cpovirk** [google/truth#192]
An internal CL is about to remove the type parameter from `OptionalSubject<T>`. This got me wondering: Do we need the type parameters on *any* of our collection subjects?

- `MultimapSubject` _kind of_ needs `<K>` so that it can ensure that calls to `valuesForKey()` work, but I think we should permit any `Object` there (and do an unsafe cast) so that users can perform assertions on a `Multimap<?, ?>`. This should be fine: `Multimap.get()` requires a `K` only because it allows callers to then insert into the collection. Here, that's not possible.

- `IterableSubject` needs `<T>` (and hence `MultimapSubject` needs `<V>`) so that we can offer `isOrdered(Comparator<? super T>)`. We could always go with `Comparator<?>`. This could fail at runtime, but maybe it's worth it if it lets us get rid of the type parameter? This is tougher.

Now, I would hate to remove the type parameters only to have to add them back in....

**Comment by kluever** [comment]
Yep, I think you're right...they should all be ripped out, but the Comparator issue gave me a bit of pause.

**Comment by kluever** [comment]
This is fixed and will be mirrored out shortly.

**Comment by PaulWoitaschek** [comment]
What is the reason behind this change?

It makes using truth more complicated and error prone.

For example before this change, type inference could be used and the api made sure that you compared objects with the same type.

```kotlin
    assertThat(actual).containsExactly(
        Optional.empty(),
        Optional.of(data),
        Optional.of(newData),
        Optional.empty()
    )
```

Now, one has to remember the type the `IterableSubject` expects and specify it manually.

```kotlin
    assertThat(actual).containsExactly(
        Optional.empty<FoodPlanData>(),
        Optional.of(data),
        Optional.of(newData),
        Optional.empty<FoodPlanData>()
    )
```

**Comment by cpovirk** [comment]
There should be no need to specify the types manually: The method will accept any `Object` as input. But maybe I'm misunderstanding?

It's true that the current API is error-prone (because `containsExactly` accepts any `Object`, rather than require `T`, though that was true before this specific change), since you can pass an object of the wrong type. We expect to do something about that, but that's still probably a couple quarters away. Sadly, simply requiring `T` has its own downsides:

```
hasContentsAnyOrder(java.util.List<java.lang.Object&java.io.Serializable&java.lang.Comparable<?
extends java.lang.Object&java.io.Serializable&java.lang.Comparable<?>>>...)
in org.junit.contrib.truth.subjects.IterableSubject<capture#106 of ?
extends org.junit.contrib.truth.subjects.CollectionSubject<?,java.util.List<java.lang.Object&java.io.Serializable&java.lang.Comparable<?
extends java.lang.Object&java.io.Serializable&java.lang.Comparable<?>>>,java.util.Collection<java.util.List<java.lang.Object&java.io.Serializable&java.lang.Comparable<?
extends java.lang.Object&java.io.Serializable&java.lang.Comparable<?>>>>>,java.util.List<java.lang.Object&java.io.Serializable&java.lang.Comparable<?
extends java.lang.Object&java.io.Serializable&java.lang.Comparable<?>>>,java.util.Collection<java.util.List<java.lang.Object&java.io.Serializable&java.lang.Comparable<?
extends java.lang.Object&java.io.Serializable&java.lang.Comparable<?>>>>>
cannot be applied to
(java.util.List<java.lang.Object>,java.util.List<java.lang.Object>,java.util.List<java.lang.Object>,java.util.List<java.lang.Object>)
    ASSERT.that(Sets.cartesianProduct(x, y)).hasContentsAnyOrder(exp1,
exp2, exp3, exp4);
```

> cartesianProduct() isn't returning a Set of `List<Object>`; it's
> returning a Set of `List<Object&Serializable&Comparable<...>>`.
> Luckily, I know the magic words (a "`<Object>`" on the
> cartesianProduct() call), but I suspect that many people won't get
> past the C++-template error messages.
