### ISSUE TITLE
Questionable usage of @Nullable

### ISSUE THREAD

**Issue by ooxi** [google/truth#194]
The google truth codebase uses `@Nullable` from JSR305 quit a bit but that specification request will [likely not included in the Java core](http://stackoverflow.com/questions/2289694/what-is-the-status-of-jsr-305).

Shouldn't the annotations be replaced by something in the JDK like `Optional`?

**Comment by kluever** [comment]
Even though JSR305 isn't going to make it into JDK, we still use it in many of our projects (Truth, Guava, etc). Many of our static analysis tools (http://errorprone.info and `NullPointerTester`) look for the `@Nullable` annotation and understand it.
