### ISSUE TITLE
Add `.hasMessageContaining("blah")` to ThrowableSubject

### ISSUE THREAD

**Issue by cgruber** [google/truth#197]
A lot of error messages are tested with assertThat(foo.getMessage()).contains("blah").  This "less brittle than equality" option should exist as a first-class type on ThorwableSubject.

**Comment by kluever** [comment]
Related to #108 (which we closed). Again, just waiting on a final API decision.

**Comment by cgruber** [comment]
Dupe then.

**Comment by dimo414** [comment]
Reference #252 which actually adds a message-contains check option.
