### ISSUE TITLE
Crazy idea: Require users to explicitly choose inOrder() or inAnyOrder()

### ISSUE THREAD

**Issue by cpovirk** [google/truth#200]
I've said on occasion that users are going to pick the first assertion that sounds right. This is why I've pushed against `isAssignableFrom`, `containsAllOf`, and so forth.

I have had the same feeling about `containsExactly` for a while. How many users think that `containsExactly("a", "b", "c")` must mean that the input is, well, "exactly a, b, c?" I can imagine that even experienced users who know about `inOrder()` may occasionally make this mistake because it's easy.

I had figured that there was nothing we could do about this because we aren't going to want `containsExactlyInOrder` + `containsExactlyElementsInInOrder` + `containsExactlyAnyOrder` + `containsExactlyElementsInAnyOrder` (and similarly for the other methods that support `inOrder`). But it occurs to me now that there is another option: Have only `containsExactly` and `containsExactlyElementsIn`, but make them `@CheckReturnValue` to force users to call either `inOrder()` or a new hypothetical `inAnyOrder()` method.

Now users are confronted with the ordering decision.

All that said, I think this is probably more trouble than it's worth:

- The migration is large. I'm sure we can manage it internally, but it will take time, and it's a pain for external users. (But if we do want to do it, we should do it soon, since it will only get harder.)
- External users who don't use a `@CheckReturnValue` checker may write tests that don't test anything at all. This is even worse than forgetting to check order when you should.
- This makes unordered assertions longer than they are. It even makes them longer then ordered assertions. That's sad. I can even imagine that some users might be tempted to write `inOrder()` when order isn't guaranteed, leading to problems with things like hash ordering.

**Comment by cgruber** [comment]
> External users who don't use a @CheckReturnValue checker may write tests that don't
> test anything at all. This is even worse than forgetting to check order when you should.

I think this is the trump-card.  I simply don't think we can rely on open-source users to be benefiting from static analysis, so we should, yes, make sure we help them benefit if they do, but not assume it, and make safer assumptions where possible.

**Comment by jbduncan** [comment]
Why not "invert" the meaning of `containsExactly` and make it check for things in order, and replace `inOrder` with an operation that checks for no particular ordering, like `inNoParticularOrder`?

Hmm, but then again this would break people's tests since it would be a significant API change. But would such an API change be that bad for a (pre-)1.0 release, especially if it's documented in the release notes?

**Comment by jbduncan** [comment]
And also I'm not sure if this is possible from an implementation perspective...

**Comment by cpovirk** [comment]
Yeah, I don't think we can find an implementation that works.

Anyway, closing.
