### ISSUE TITLE
Very minor website doc issue ad "Custom Error Messages"

### ISSUE THREAD

**Issue by reinholdfuereder** [google/truth#201]
// Reports: My custom Message
assert_().withFailureMessage("My arbitrary custom message")
    .that(myBooleanResult).named("hasError()").isTrue();

The first line should presumably be:
// Reports: My arbitrary custom message

**Comment by kluever** [comment]
Thanks!

@cgruber - can you update http://google.github.io/truth/ with the change when you get a chance?

**Comment by cgruber** [comment]
We've replaced the external site with synced internal/external documentation, so that bit has gone away.  We'll be fleshing out the docs this quarter.  Marking this bug closed as obsolete.
