### ISSUE TITLE
Consider removing self type <S> from Subject

### ISSUE THREAD

**Issue by cpovirk** [google/truth#202]
Part of our War on Type Parameters :)

Other parts:
- https://github.com/google/truth/issues/192 (to remove `<T>` from `IterableSubject` and so forth)
- Internal bug 16702475 (to remove `<T>` from `Subject` in favor of letting each subclass store (or at least cast) the subject itself)

The new part:
- this bug (to remove `<S>` in favor of making each subclass override `named()`)

Motivation:

a) IIRC, we have a history of writing things like...

    public class IterableSubject<T, C extends Iterable<T>>
        extends Subject<IterableSubject<S, T, C> S, C> {

...instead of...

    public class IterableSubject<S extends IterableSubject<S, T, C>, T, C extends Iterable<T>>
        extends Subject<S, C> {

...which leads to problems when users try to extend the subject.

b) We need ugly stuff like this...

      @SuppressWarnings({"unchecked", "rawtypes"})
      static <T, C extends Iterable<T>>
          IterableSubject<? extends IterableSubject<?, T, C>, T, C> create(
              FailureStrategy failureStrategy, @Nullable Iterable<T> list) {
        return new IterableSubject(failureStrategy, list);
      }

...instead of...

    new IterableSubject(failureStrategy, list);

Maybe it would be simplest to eliminate the self type entirely? This would require subclasses to override `named()`. We could solve much of the problem by making it `abstract`, but there's still the problem of making sure that users who then *extend* something like `IterableSubject` remember to override it again. We could probably have some static analysis or a `SubjectTester` for this. Possibly we should anyway, though we'll have to make sure people use it.

**Comment by cpovirk** [comment]
Related: `BooleanSubject` uses failure messages like "The subject was expected to be true but was false." If we decide that the "the subject" should be "the actual value," this would need a rewrite. The easiest option is probably "the value." I suppose that "the value" could work for `getSubject()`, too: `getValue()`.

**Comment by cpovirk** [comment]
Related: I think I floated the idea of `named(String pattern, Object... args)` at some point. If we add it, then we'd want to ask all `Subject` authors to introduce overloads with the appropriate return type.

**Comment by kluever** [comment]
I took a stab at this internally...the CL got pretty hairy: CL/109729808

We're basically duplicating these lines to every subject:
```
  @Override
  public FooSubject named(String name) {
    setCustomName(name);
    return this;
  }
```

There are ~500 subclasses of Subject already internally, so this would be a pretty substantial undertaking.

**Comment by cpovirk** [comment]
Thanks, Kurt :(

Below I eventually suggest that we revisit the `named()` design entirely. Before that, I try to make things work as it is.

The "good news" is that the only `Subject` types that we *really* need `named()` are the ones on which it's used. I mean, they probably all "should" define it, but code will compile without it as long as no one tries to use it. That at least means that we don't need an atomic change to every `Subject` out there, nor will our external users.

Of course, if someone later tries to use it, that will be bad news: The only assertions available after the call will be those on `[Object]Subject`, and the user might well not realize why. Perhaps, to make this less confusing, we should *remove* `named()` from `[Object]Subject`. Then, the problem users will have is "`named()` doesn't exist on this type." Presumably that is easier for them to understand and fix.

Users may still have problems, though, with "multi-level extension": A type that extends `IterableSubject` will inherit an `IterableSubject`-returning `named()` method, and we're back to the problem we had before. This should at least be less common, but it's still likely to confuse some people.

Now, we can write an Error Prone check for the "missing" `named()` method. But I don't whether that the Error Prone team would accept it as a universal compile error (though we could ask). We could have it on optionally, though, and we could use it to add `named()` automatically to existing `Subject` types. (Or we could probably do the same with `sed`.)

I thought of another attempt at a workaround that I also don't love: We could set a policy of "never inherit from a concrete `Subject`." Then we would have a hierarchy like this:

- `AbstractObjectSubject`: new name for today's `Subject`, `abstract`, `named()` is either absent or `abstract`
- `ObjectSubject`: new name for today's `DefaultSubject`, `final`, `named()` returns `ObjectSubject`
- `AbstractIterableSubject`: new name for today's `IterableSubject`, `abstract`, doesn't define `named()`, extends `AbstractObjectSubject`
- `IterableSubject`: extends `AbstractIterableSubject`, `final`, contains only a definition of `named()`

Basically, every extensible class would come in an `AbstractFooSubject` and a `FooSubject`. Direct users would use the latter, and extensions would use the former.

What do we get out of all of this? Since we would define `named()` only in concrete classes, we never inherit a "bad" version from a superclass. Now, users can still, when prompted to define `named()`, accept the default signature, which returns `AbstractObjectSubject`. But maybe they at least have a better chance at doing the right thing? But then they also need to follow this pattern themselves. And it's an unnatural pattern, so they probably won't do so.

Some more bad news: If we can't remove `<S>`, then we really should put back some of the big `IterableSubject` generics that you just removed (maybe not all of it, but enough that users will need to write something like `IterableSubject<IterableSubject>`. Otherwise, users can't extend `IterableSubject` correctly. (This is why we had trouble with those few classes that did so.) Basically what's going on now is that `IterableSubject` declares (a) that `named()` is going to return an `IterableSubject` and (b) that it works with any `Iterable<?>`. The former we can work around by redeclaring `named()` in the subclass. The latter we're stuck with, so users can't extend `IterableSubject` to write a subject for `Iterable<MyType>` unless they use unchecked casts. That's not the end of the world, but I would expect some users to have trouble with it, especially since we'll be doing the "wrong" thing. (It's also "solvable" by adopting my "`AbstractIterableSubject`" scheme above, but I still hope we don't need to do that.)

The option that I'm actually favoring at the moment is this: Change the "specify a name" API from `assertThat(expectedFoo).named("foo")` to `assertThat(expectedFoo, "foo")`. This feels natural enough to me: It's similar to APIs like `checkNotNull` (though a little different, since we're specifying a name, not a full message). It's even reasonable enough English: "Assert that expectedFoo, 'foo," is...." "Assert that result, 'the return value of hasNext() when iterator is exhausted,' is false."

**Comment by kluever** [comment]
Another option that has a nice parallel with `assertWithMessage("blah blah blah")`:
`assertWithName("foo").that(myFoo).isEqualTo(FOO);`

**Comment by cpovirk** [comment]
I guess that both his solution and my solution may prevent users from specifying both a failure message and a name. That's perhaps not ideal but probably acceptable.

**Comment by cpovirk** [comment]
We see maybe 20 such callers internally (plus ~10 that seem to misunderstand what `named()` does, plus a couple in Truth's own tests). We think they can probably get by with just a failure message or something, though we haven't tried yet.

**Comment by kluever** [comment]
A few issues with `assertThat(value, "name")`:
* this would require doubling the number of existing overloads (not a huge deal, but it's something...)
* the same problem we've seen with `Preconditions` and `MoreAsserts` and `JUnit` where people reverse the ordering and shoot themselves in the foot (e.g., `assertThat("a name", myString).startsWith(...);`)

**Comment by cpovirk** [comment]
If we do leave the self type, let's add an explicit `@param` tag for it. Even though it looks obvious in context, it looks weird to have `IterableSubject<T>` where `<T>` isn't the type of elements in the underlying `Iterable`.

(Will `IterableSubject` inherit the `@param` from `Subject`, or will we need to put the next there (and in `MapSubject`, etc.)? I could imagine that Java sees the two Ss as "different" types.)

**Comment by cgruber** [comment]
I'm going to mark `@param` on it.

Given that we're going to entertain the idea of describedAs() as a fully-replacing equivalent to named() that would mean extra things to override.

I think we can eliminate a lot of type parameters, but I think this one probably needs to stay.  And a lot of the complexity should be hidden if we implement the subject factory generator. 

Also... it generally seems to be the case that "war on X" tends to increase the presence of "X" - (c.f. war on drugs, war on poverty, war on terror), so we might want to reconsider warring against type parameters.

**Comment by PaulWoitaschek** [comment]
I don't understand this. This makes the usage of truth really really error prone.
It occures to me so many time that I do sth like:

```kotlin
val peter = User("peter")
assertThat(peter).isEqualTo("peter")
```

That compiles but does not make any sense.

**Comment by cpovirk** [comment]
Fixing that error, unfortunately, is more difficult than a type parameter. The closest we can get with Java itself is to make every instance of a `Subject` subclass parameterized. So we'd have `ObjectSubject<User>`, `IterableSubject<Iterable<String>>`, etc. And then we'd change `isEqualTo(Object)` to `isEqualTo(T)`. That much might be doable (though the generics would get more complex), but it's still not quite right: `isEqualTo(T)` is unnecessarily strict, for reasons analogous to those discussed in https://smallwig.blogspot.com/2007/12/why-does-setcontains-take-object-not-e.html and https://errorprone.info/bugpattern/CollectionIncompatibleType#footnote-would-requiring-e-have-been-better

The best solution we've found for this is to use [Error Prone](https://errorprone.info/), specifically its [TruthIncompatibleType](https://errorprone.info/bugpattern/TruthIncompatibleType) check. It's not perfect, but I believe it would catch your specific error -- at least if we're talking Java, which it looks like we might not be :) Hopefully we'll see some "Error Prone but for Kotlin" tools become available.
