### ISSUE TITLE
Policies for extensions to Truth

### ISSUE THREAD

**Issue by cpovirk** [google/truth#212]
We've started discussing this internally in a doc. I'm filing this bug so that we can track it for 1.0.

**Comment by cgruber** [comment]
Does this mean policies for the extensions subproject?  Or did you mean policies related to the SPI that aren't explicitly part of the code interfaces?

**Comment by cpovirk** [comment]
I think I meant the extensions subproject. Basically, I just wanted something in the bug tracker as a reminder of the work you were already doing.

**Comment by cgruber** [comment]
Got it. Thanks.

**Comment by cgruber** [comment]
I'll propose some wording for this.

**Comment by cpovirk** [comment]
I don't think we have a lot concrete in mind here anymore, and we've released our existing extensions, so let's call this fixed.
