### ISSUE TITLE
Rename OptionalSubject to GuavaOptionalSubject to make room for java.util.Optional

### ISSUE THREAD

**Issue by cpovirk** [google/truth#215]
Depending on how much time and how many releases we have between now and 1.0, we might even get the new `java.util.Optional` subject in under the reused name "OptionalSubject." But the important thing -- if we think that the `Subject` class names are important enough to worry about at all -- is to stop calling the Guava one "OptionalSubject."

**Comment by kluever** [comment]
I don't think subject class names are particularly important, but this sounds reasonable.

**Comment by kluever** [comment]
Fixed internally, will get mirrored out at next push.

**Comment by cpovirk** [comment]
(For the record, we currently have the `java.util.Optional` version named "JavaOptionalSubject" (submitted internal CL 99036744).)
