### ISSUE TITLE
support for expecting exceptions

### ISSUE THREAD

**Issue by christophsturm** [google/truth#219]
I have been using assertj-core previously and am now trying truth for a new project.

One thing that I'm missing is support for expecting exceptions in a code block

<pre>
assertThatThrownBy((()->myMethodThatThrows()).isInstanceOf(NullPointerException.class);
</pre>

this is obviously dependent on java 8, but would be really nice to have.

**Comment by kluever** [comment]
Interesting idea...it'll be a while until Truth requires Java8, but we'll keep this in mind.

**Comment by christophsturm** [comment]
maybe put the java8 stuff into a separate jar?

**Comment by cgruber** [comment]
We will be putting java8 stuff into an extension... but it's worth noting that we CAN just implement this in Java7, but people would be forced to create a single-abstract-method interface impl, like this:

Assuming:
```
  public interface ThrowingRunnable {
    void run() throws Throwable;
  }
```

One could write:

```
ThrowingRunnable code = new ThrowingRunnable() {
  @Override public void run() throws Throwable {
    objectToTest.doThingThatShouldThrow();
  }
}
assertThat(code)
    .throwsException(FooException.class)
    .withMessageContaining("Blah")
    .withCause(SomeOtherException.class);
```

Then the Java8 user can simply use this with lambdas like this:

assertThat(() -> objectToTest.doThingThatShouldThrow())
    .throwsException(FooException.class)
    .withMessageContaining("Blah")
    .withCause(SomeOtherException.class);
```

as the @christophsturm pointed out. 

So this itself doesn't need to be in java8, since it requires no java8 feature, it just benefits from one.

**Comment by jbduncan** [comment]
I adopted Truth at the start of one of my projects too, and I've just come across a situation today where having something like this would be very useful for me.

Are there any plans yet to implement throwable-catching assertions along the lines of what this issue's requesting?

**Comment by jbduncan** [comment]
(To add to @christophsturm's opening comment, I've noticed that JUnit 5 implements something similar with `assertThrows`.)

**Comment by kluever** [comment]
FWIW, we'll probably end up endorsing JUnit's new `assertThrows()` and `expectThrows()` APIs. `expectThrows()` works particularly well with Truth (especially with our soon-to-be-released expanded `ThrowableSubject`).

**Comment by jbduncan** [comment]
Hi @kluever, AFAICT `expectThrows` has been deprecated now and `assertThrows` now essentially does what `expectThrows` used to do (which was to return the expected exception upon catching it).

But I understand the sentiment of your comment. I'll probably have to brace myself to migrate from JUnit 4 to 5 in the near future then.

**Comment by cgruber** [comment]
If expectThrows is deprecated, and we don't find something in the core APIs
of JUnit that are amenable to Truth, then we can always make our own - it's
a fairly simple API.

**Comment by sbrannen** [comment]
> If expectThrows is deprecated, and we don't find something in the core APIs
of JUnit that are amenable to Truth, then we can always make our own - it's
a fairly simple API.

Actually, `expectThrows` was simply renamed to `assertThrows`, and the old `assertThrows` was removed. 

In other words, if the original `expectThrows` in JUnit Jupiter suited your needs, then the current (as of 5.0 M3) `assertThrows` will, too. 😉

**Comment by dimo414** [comment]
I think at this point this should be closed - `expectThrows` / `assertThrows` works nicely, and [`ThrowableSubject`](http://google.github.io/truth/api/latest/com/google/common/truth/ThrowableSubject.html) allows you to make assertions on the returned exception.

Tangentially related, there's also now [`ExpectFailure`](http://google.github.io/truth/api/latest/com/google/common/truth/ExpectFailure.html) for expecting Truth failures (as opposed to expected exceptions), e.g. when testing custom `Subject` implementations.
