### ISSUE TITLE
Back out support for @Nullable format/template?

### ISSUE THREAD

**Issue by cpovirk** [google/truth#225]
I think this support is a holdover from the days when we thought it was wise for `Preconditions` to accept any old `Object` as the message. Later, we realized that that led users to make mistakes. (We may have even introduced some Error Prone checks to catch them.)

With Truth, we decided to take a hard line on messages in another context: If the user passes "%s" as the template with no args, we blow up. I see this case as similar: If the users passes a null format, we should blow up. Users who really want that can say `assertWithMesage("%s", foo)` or whatever.

**Comment by cgruber** [comment]
Thankfully, `.named(...)` doesn't suffer from this.

**Comment by cpovirk** [comment]
We should also consider whether we want the multiple overloads of `[assert]WithMessage` that we have currently:

https://google.github.io/truth/api/latest/com/google/common/truth/Truth.html#assertWithMessage-java.lang.String-

If we do want multiple, then maybe we want to follow the `Preconditions` model of making the one-arg method accept `Object`?

**Comment by cpovirk** [comment]
> If we do want multiple, then maybe we want to follow the `Preconditions` model of making the one-arg method accept `Object`?

We now have https://github.com/google/truth/issues/498 for that.
