### ISSUE TITLE
Research the OpenTest Alliance common assertions and feed-back

### ISSUE THREAD

**Issue by cgruber** [google/truth#226]
Initially conceived of here: junit-team/junit-lambda#12 and moved to ota4j-team/opentest4j#1, this project presumes to supplant the typical use of AssertionError with a standard set of articulated exceptions more suited to testing, rather than relying on arbitrary per-testing-framwork sub-classes.

At this point, we need to investigate the semantics of the included APIs and ensure we can support them in the semantics of Truth, or that we have the ability to opt-out in a clear and obvious (to the user) way.

So, steps are:
- [x] Evaluate the assertions and other APIs
- [ ] Work up a prototype based on the snapshot
- [ ] Feedback any issues or concerns, especially adoption blockers
- [ ] Help push through a release artifact (if we can)
- [ ] Update and integrate the assertions into Truth.

Some items for consideration:
- Can these largely be fit into a FailureStrategy paradigm?
- Should these be the default, or should these be supported in a truth extension?
- What other design implications arise from these APIs. 
- Should we push Truth 1.0 out to support them, or let these be a Truth 1.1
  - AssertionFailedException extends AssertionError so it seems that adoption would not be a breaking change, even if adoped into the core artifact.

**Comment by sbrannen** [comment]
@cgruber, thank you for creating this issue for Truth.

We're really looking forward to your feedback, especially with regard to any adoption blockers you discover.

> AssertionFailedException extends AssertionError so it seems that adoption would not be a breaking change, even if adoped into the core artifact.

Yes, that is in fact one of our primary goals: assertion errors in the OTA will in fact still be a subclass of `AssertionError`, thereby allowing testing frameworks to rely on the contract of `AssertionError` (if that's all that's required) or to make use of features of specific subclasses of `AssertionError` (if that provides additional value to the user, IDE, build tool, etc.).

**Comment by cgruber** [comment]
Funny you mention it.  @kevinb9n actually asked hopefully if this new exception library could finally dislodge us from using AssertionError for testing.   I told him apparently not, and he sighed. :)

**Comment by cgruber** [comment]
Actually, I'll open that as an issue.  It might be a design goal, but it might be worth discussing.

**Comment by cpovirk** [comment]
They've released a 1.0, and it's likely to be suitable for our needs. The question is just migration. Let's use https://github.com/google/truth/issues/333 for tracking that.
