### ISSUE TITLE
Failing the test without exception in console

### ISSUE THREAD

**Issue by cambiph** [google/truth#227]
Hello,

I know this is kind of a weird request but I am pitching it to you anyways.
We have a small monitoring utility in Java that uses Junit to test some web interfaces.
When a condition is not met, the test fails, obviously.
But we want to display the results with a nice message on a monitor.
Problem is when we use the console, the  exception is shown.

A logical alternative would be to write to a file and display the results of the file.
However, we want to run the tests multi-threaded so writing to a file is kind of a bad idea.

That is why I was searching for a strategy to fail a test and not throw an exception to the console.
We can catch the exception but then the test passes, we don't want that.

Any ideas?
Thanks in advance!
Regards

**Comment by cgruber** [comment]
Well, you could make a custom FailureStrategy that simply throws away the
"cause" (assuming you wanted to use existing Subjects for your test).
Though I would be cautious.  We're reworking the FailureStrategy API, and
while we'll have some compatibility for a while, if you can hold off for a
bit, it'd be better to code it to the newer APIs.

**Comment by cambiph** [comment]
Ok, thanks.
For now I shall check out the FailureStrategy.
