### ISSUE TITLE
Reference to deleted 'thatEach' on http://google.github.io/truth/usage

### ISSUE THREAD

**Issue by dbort** [google/truth#238]
IteratingVerb (which provides thatEach()) was removed in commit 60342bc, but the docs at http://google.github.io/truth/usage/#categorically-testing-the-contents-of-collections still refer to it.

**Comment by cgruber** [comment]
Will do.

**Comment by leeavital** [comment]
Pardon me if this is the wrong place to ask, but is there an alternative to thatEach? It's a very useful looking function.

**Comment by cgruber** [comment]
We are looking at a replacement feature post 1.0 release.  It'll be
similar, but generated at compile time with the subject.

**Comment by cgruber** [comment]
Closing this, since that document is now obsolete, in the current website.
