### ISSUE TITLE
Add a subject for java.util.Optional

### ISSUE THREAD

**Issue by PhilippWendler** [google/truth#245]
Please add a subject for `java.util.Optional`. I saw it mentioned in #215 and would like to be able to use it in our projects.

**Comment by kluever** [comment]
Thanks. We've got this on our radar, but we have to ensure that Java 7 users can continue to use Truth as well.

**Comment by jbduncan** [comment]
This might be worth adding as a separate project to the `extensions/` folder until Google is ready to move to Java 8.

**Comment by jbduncan** [comment]
Oh, never mind! I just saw https://github.com/google/truth/issues/206#issuecomment-225924910, which explains this is currently being worked on.

**Comment by cgruber** [comment]
It is indeed. Should be out this month.

**Comment by jbduncan** [comment]
Fantastic @cgruber! Looking forward to it.

**Comment by cgruber** [comment]
Fixed in ec88860123af376bf4dc432bf4781f001b3c66f4
