### ISSUE TITLE
BooleanSubject failure messages are confusing when subject is null

### ISSUE THREAD

**Issue by dborowitz** [google/truth#248]
This test:
```java
Boolean b = null;
assertThat(b).isFalse();
```
results in "The subject was expected to be false, but was true". No it's not; it's null.

Similarly, this test:
```java
Boolean b = null;
assertThat(b).isTrue();
```
results in "The subject was expected to be true, but was false".

**Comment by kluever** [comment]
Thanks! This was fixed internally (CL/116906970) and should be mirrored out with the next release.

**Comment by talios** [comment]
@kluever tangental to this specific issue, any eta for the next release?

**Comment by kluever** [comment]
@cgruber is working towards a 1.0 release hopefully soon

**Comment by cgruber** [comment]
I'll release an interim release probably next week.
