### ISSUE TITLE
Provide a SortedMap and/or NavigableMap Subject

### ISSUE THREAD

**Issue by dimo414** [google/truth#249]
I'd like to be able to assert things about the order of a `NavigableMap` (specifically I'm interested in the `firstEntry()`, but I can imagine wanting to assert on other similar facts about the structure of an ordered map.

**Comment by kluever** [comment]
This seems like a reasonable thing to add.

**Comment by cgruber** [comment]
Can you please brainstorm some other propositions you imagine using?  We don't want to kitchen-sink the thing, but it would be nice to get a sense of how you would use it.  Maybe some code samples where you're extracting the value currently and testing that, and what you would like to see replacing it?  (We're on board that it's a good feature - just want to flesh it out a bit)

**Comment by dimo414** [comment]
I only just ran into a use-case where I needed to assert something about the ordering of a `NavigableMap`, so I don't have a lot of concrete examples (yet). At a minimum I'd want to follow `MapSubject`'s `containsKey()` and `containsEntry()` methods with `hasFirst[Key/Entry]()` and `hasLast[Key/Entry]()`. This changes:

    assertThat(map.firstEntry().getKey()).isEqualTo(key);
    assertThat(map.firstEntry().getValue()).isEqualTo(value);

Into:

    assertThat(map).hasFirstEntry(key, value);

I'd also imagine supporting the search methods (`ceiling[Key,Entry]()`, `floor[Key/Entry]()`, `higher[Key/Entry]()`, and `lower[Key/Entry]()`); they're probably less critical than first/last, but they also don't feel like they increase the complexity of the API much so I'd vote to include them.

I'm not sure that there's much to do with `comparator()` - you could assert that it *has* a comparator, but that doesn't seem tremendously useful. Similarly the `[sub/head/tail]Map()` methods don't really feel necessary out of the box.

**Comment by kluever** [comment]
+1 to all of what @dimo414 said.

**Comment by dimo414** [comment]
Implemented in 8dd9b535e1.
