### ISSUE TITLE
Support partial matches (contains and/or regex) of Throwable's messages

### ISSUE THREAD

**Issue by dimo414** [google/truth#252]
`ThrowableSubject` allows you to assert `Throwable.getMessage()` matches a string exactly, but doesn't provide any further assertions. Notably this prevents substring or pattern matches which are often necessary when inspecting exceptions.

Suggest adding any/all of the following:
- `StringSubject hasMessageThat()`
- `hasMessageMatching(String/Pattern regex)`
- `hasMessageContainingMatch(String/Pattern regex)` (naming here is a little odd, but it needs to not be confused with a simple contains check)
- `hasMessageContaining(CharSequence string)`

**Comment by cgruber** [comment]
+1.

**Comment by dimo414** [comment]
a866b63de7 introduced `.hasCauseThat()`.

**Comment by kluever** [comment]
I assume we can close this now?

**Comment by dimo414** [comment]
Note `.hasMessage()` has not yet been deprecated (despite the commit message to the contrary) while we migrate internal usages. I'll close this once `.hasMessage()` is actually deprecated.

**Comment by dimo414** [comment]
`.hasMessage()` was deprecated in 3716e5af2d.
