### ISSUE TITLE
Should we call it 2.0?

### ISSUE THREAD

**Issue by cgruber** [google/truth#256]
@kevinb9n suggested to me that Truth has evolved well past what would normally be considered a 1.0 release, and with the solidification of the extension APIs and other renames and things, we're really closer to a 2.0. 

Essentially this is a pure branding question. I'm sympathetic.  Truth has been around for a long while, and has stabilized a great deal owing to its permeation throughout Google's codebase and some love from the core libraries team at google.  I'm kind of inclined to call it 2.0. 

Thoughts?  Agree?  Disagree?

**Comment by kluever** [comment]
I'm fine w/ 1.0.  I don't really see any benefit to calling it 2.0.

If we change the SPI significantly, or add significant features, then we can call that 2.0.

**Comment by ronshapiro** [comment]
I think we're pretty set on this being 1.0. Going from 0.x to 2.x seems confusing too
