### ISSUE TITLE
Put the new java8 stuff behind a profile, so it doesn't blow-up travis's java7 combos.

### ISSUE THREAD

**Issue by cgruber** [google/truth#257]

**Comment by cgruber** [comment]
Everything is working, it's just that testing against java7 breaks because it tries to build the java8 extension. That should just be skipped when running under java7, since it can't work.

**Comment by dinesh707** [comment]
Is there any advantage of creating a makefile, which trigger different maven profiles ?, so that people get a clean understanding on building

**Comment by jbduncan** [comment]
Maybe @dinesh707, but the problem with a makefile AFAICT is that it wouldn't be cross-platform, as Make is a Unix-centric tool.

If going for something like a makefile is needed, I would research alternatives like a Python script or a different build tool like Bazel.

**Comment by ronshapiro** [comment]
I imagine this is now stale?
