### ISSUE TITLE
Decide when subject classes should be final

### ISSUE THREAD

**Issue by cpovirk** [google/truth#258]
My initial reaction was:
- If the type of the "actual" is `final`, then the subject is `final`. So `StringSubject` is `final`, but `IterableSubject` is not.

But:
- Do we want to allow people to subclass a subject to add their own assertions? We've seen this done in bad ways (where people should really have written their own assertion methods or delegated (like `MultimapSubject.valuesForKey`)), but it seems believable that a team might want to add `MyStringSubject.allMatches(CharMatcher)` or something. (Of course, the team won't be able to name their entry point `assertThat` if they want to static import it, since it will conflict with the main `Truth.assertThat(String)`. But that's OK.)

And:
- Do we want to allow people to subclass a subject to add a custom string representation? Take `IterableSubject`. It needs to be non-final, anyway, for use from `MultisetSubject`. But it's also subclassed for `MultimapSubject.valuesForKey`. It seems believable that we'd someday want to subclass `StringSubject` for `ThrowableSubject.cause` (if we go that direction, which I kind of expect us _not_ to... but it serves as an example). So can we sensibly make _anything_ `final`?

This also ties in with my favorite subject, type parameters :) If we want for users to be able to add assertions to a type, then we should keep the type parameters on that type:

```
StringSubject<S extends StringSubject<S, T>> extends ComparableSubject<S, T> {
```

not:

```
StringSubject extends ComparableSubject<StringSubject, String> {
```

That way, subclasses can provide their own value for `<S>` so that `named()` returns a type with the full set of assertions.

So there are a few parts to this:
- Make a decision about what classes are `final`.
- Make a decision about which non-`final` classes we want to allow users to add assertions to (so that we know what to do with our type parameters).
- If we're keeping some classes non-`final`, probably add `final` to their declared methods. (Edit: And update constructor visibility for each type -- protected or package-private.)

**Comment by dimo414** [comment]
Is this a dupe of #217?

**Comment by cpovirk** [comment]
Ha, yes, thanks.
