### ISSUE TITLE
Testing none java generated sources

### ISSUE THREAD

**Issue by vegegoku** [google/truth#260]
I am trying to generate an HTML out fro annotated classes and i need to write unit testing for the generated .html files:

when i am generating .java files i testing them like this:
```java
Truth.assert_().about(javaSource()).that(JavaFileObjects.forResource("source class .java goes here"))
                .processedWith(new UiFormProcessor()).compilesWithoutError()
                .and()
                .generatesSources(JavaFileObjects.forSourceString("","expected generated class content goes here"));
```

and that works for me very well.

but when i am trying to generate an .html file and use the same code above, it result in an error like this 
`java.lang.AssertionError: Did not find a generated file corresponding to .java`

its seems that the generated files are expected to be java files all the time, i have been trying to figure out if i am calling the wrong methods or passing wrong arguments, but i could'nt make it work.

is there anyway to test none java generated sources like hml with this tool?

**Comment by cpovirk** [comment]
Looks like this is resolved in https://github.com/google/compile-testing/issues/99
