### ISSUE TITLE
Make IterableSubject.containsExactlyElementsIn() with an empty required collection give the same failure message as isEmpty()

### ISSUE THREAD

**Issue by llbit** [google/truth#263]
I love the Google Truth library, and I use it often in tests for checking that collections contain the right elements where the required elements are often dynamically computed. However, I think some failure messages are needlessly verbose. For example, with Truth 0.30, if I pass an empty collection to `containsExactlyElementsIn()`, I get the following type of failure message:

```
 Not true that <[foo, bar]> contains exactly <[]>. It has unexpected items <[foo, bar]>
```

It is quite unnecessary to list the unexpected items when the required collection is empty, because they are identical to the subject collection. After thinking about this briefly, I think it would be nicer if `containsExactlyElementsIn()` gave the same failure message as `isEmpty()` when the required collection is empty. That would turn the above failure message into this:

```
Not true that <[foo, bar]> is empty
```

There might be some value to having all the failure messages from `containsExactlyElementsIn()`, and by extension `containsExactly()`, use the same format - it makes those assertions easy to separate from the `isEmpty()` assertion failures. However, I often have large collections as subject to `containsExactlyElementsIn()` and then it can be cumbersome to read the output in the console.

My use case is maybe a bit uncommon because the required collection is dynamically computed, so I don't know statically if I should call `isEmpty()` or `containsExactlyElementsIn()`. Of course it would be possible to make my tests call either or depending on the size of the required collection.

**Comment by kluever** [comment]
This is certainly a reasonable request.

**Comment by llbit** [comment]
I tried a quick shot at altering the behavior of `containsExactlyElementsIn()` by adding this:

```diff
diff --git a/core/src/main/java/com/google/common/truth/IterableSubject.java b/core/src/main/java/com/google/common/truth/IterableSubject.java
index 36ff5f9..f27b230 100644
--- a/core/src/main/java/com/google/common/truth/IterableSubject.java
+++ b/core/src/main/java/com/google/common/truth/IterableSubject.java
@@ -281,6 +281,15 @@ public class IterableSubject extends Subject<IterableSubject, Iterable<?>> {
     Iterator<?> actualIter = actual().iterator();
     Iterator<?> requiredIter = required.iterator();
 
+    if (!requiredIter.hasNext()) {
+      // The required collection is empty, so we can call isEmpty() to generate a simpler failure
+      // message when the subject is non-empty.
+      isEmpty();
+      // If we reach this point the subject was empty, so we can return because this method should
+
+      return IN_ORDER;
+    }
+
     // Step through both iterators comparing elements pairwise.
     while (actualIter.hasNext() && requiredIter.hasNext()) {
       Object actualElement = actualIter.next();
```

I tried to run the tests with Maven, but the build does not seem to work:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.0.2:testCompile (default-testCompile) on project truth: Compilation failure: Compilation failure:
[ERROR] /home/jesper/.m2/repository/com/google/guava/guava-gwt/20.0/guava-gwt-20.0.jar(com/google/common/collect/AbstractIterator.java):[64,16] error: duplicate class: com.google.common.collect.AbstractIterator
[ERROR] 
[ERROR] /home/jesper/.m2/repository/com/google/guava/guava-gwt/20.0/guava-gwt-20.0.jar(com/google/common/base/Optional.java):[291,19] error: cannot access AbstractIterator
[ERROR] -> [Help 1]
```

**Comment by kluever** [comment]
Yep, that's exactly the solution that I had as well :-)

Not sure what the Guava error is, but I'll make sure it's passing and get this change submitted internally. Thanks!

**Comment by kluever** [comment]
OK, this is fixed internally and will be mirrored out on our next sync.

Thanks for the issue report!

**Comment by llbit** [comment]
Awesome! Thanks for adding this!
