### ISSUE TITLE
hasSize - NoSuchMethodError

### ISSUE THREAD

**Issue by aponhcet** [google/truth#279]
Hi there,
Using version

com.google.truth
truth
0.31
test

When asserting the size of a collection - I tried ArrayList and SortedMap - I got the following error.

Downgrading to 0.30 fix it.
Let me know if you need extra info.

java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)V

at com.google.common.truth.FailureContext.<init>(FailureContext.java:40)
at com.google.common.truth.AbstractVerb.<init>(AbstractVerb.java:35)
at com.google.common.truth.TestVerb.<init>(TestVerb.java:49)
at com.google.common.truth.TestVerb.<init>(TestVerb.java:41)
at com.google.common.truth.TestVerb.<init>(TestVerb.java:37)
at com.google.common.truth.Truth.<clinit>(Truth.java:76)
at

**Comment by cpovirk** [comment]
It sounds like you have an older version of Guava on your classpath than Truth expects.

**Comment by twyatt** [comment]
@aponhcet not sure if it's the same issue you were seeing but I was having the same error when running JUnits from Android Studio. Not a solution, but may offer hints as to what is going on: I found that running the same tests from command line worked for me.
`./gradlew test`

Unfortunately I was only able to get the JUnits to run from Android Studio if I downgraded to truth 0.30 as you did.

**Comment by dimo414** [comment]
@twyatt @aponhcet can you share the version of Guava you're using, as well as the version of Truth? As cpovirk said upgrading your Guava version will likely allow you to keep using the newer versions of Truth.

**Comment by feedm3** [comment]
This also happens when you compare 2 objects (obviously):

```
final Object object = new Object();
Truth.assertThat(object).isEqualTo(object);
```

Problem can be fixed by updating the guava dependency.

**Comment by aponhcet** [comment]
Sorry , I am coming back a bit late on this. If I remember well the Guava version on that project was 15.0. 
As indeed it is quiet old it may common class in the 2 lib.

I guess this can be close as upgrading guava fix it
