### ISSUE TITLE
assertThat(Path) is ambiguous 

### ISSUE THREAD

**Issue by cgrushko** [google/truth#285]
Since `Path` is `Iterable`, `assertThat(Path)` is ambiguous between `Object` and `Path`. 
The workaround I currently use is cast the subject to an `Object`.

I think this can be solved by adding an overload

```java
  public static Subject<DefaultSubject, Object> assertThat(Path p) {
    return assertThat((Object) p);
  }
```

**Comment by dpursehouse** [comment]
I solved this by adding a custom [PathSubject](https://gerrit.googlesource.com/gerrit/+/master/gerrit-test-util/src/main/java/com/google/gerrit/extensions/common/PathSubject.java).

IIRC casting the `Path` to an `Object` worked, but resulted in a "redundant cast" warning in Eclipse.

**Comment by kluever** [comment]
@cgdecker was working on a `PathSubject` a while ago...Colin?

**Comment by dimo414** [comment]
At a minimum we should add an overload to `Truth` that takes a `Path`, to avoid this annoying and confusing error. Even if it just returns `Subject`, or a `PathSubject` with no additional methods, that's clearly better than the status quo.

**Comment by ronshapiro** [comment]
@cgdecker is this specific to Jimfs, or can it be moved into Truth?

https://github.com/google/jimfs/blob/3299e69f75cf524e6d101d88e8c202c1b24bf25a/jimfs/src/test/java/com/google/common/jimfs/PathSubject.java

**Comment by dimo414** [comment]
The problem (which I ran into while trying to add a stub `PathSubject`, cl/156909203) is that Truth still needs to support builds like Android and J2CL that don't necessarily have `java.nio.file` yet. I'm not sure if there's a good solution short of creating a java7 extension (which would make me sad :( ).

**Comment by ronshapiro** [comment]
What about the Java 8 extension? We'd be losing out on Java 7 environments that aren't Android/J2CL, but it might be a good-enough path forward.

**Comment by dimo414** [comment]
We can look into pulling the assertions in JimFS's [`PathSubject`](https://github.com/google/jimfs/blob/master/jimfs/src/test/java/com/google/common/jimfs/PathSubject.java) over to Truth8 now, but ironically JimFS won't be able to use it (since it requires Java 8).

**Comment by cgdecker** [comment]
FWIW, while the Jimfs `PathSubject` covers a lot of things that you might want to test about files, it's a bit more oriented toward ensuring that the `FileSystem` and `Path` implementations are correct than toward what users need. And it does do some "clever" things with methods like `and()` that I think we'd want to avoid in an official Truth subject. Anyway, it could still be a decent basis.
