### ISSUE TITLE
Subjects for java.util.concurrent.atomic types such as AtomicBoolean etc.

### ISSUE THREAD

**Issue by vorburger** [google/truth#307]
Assuming e.g. an:

    AtomicBoolean eventReceived;

would it make sense to be able to directly write:

    assertThat(eventReceived).isTrue();

instead of as currently having to do:

    assertThat(eventReceived).isEqualTo(new AtomicBoolean(true));

Would a pull request with a contribution for this be welcome?

**Comment by cpovirk** [comment]
I would recommend:

    assertThat(eventReceived.get()).isTrue();

We generally add subjects only when the subject lets us provide additional failure information (like the missing values in a collection) or richer operations (like whether the value is in a range). Here, the message would be the same as what `BooleanSubject` provides, and so too would the operation (`isTrue`).

**Comment by vorburger** [comment]
Oh I see, right.. this really would be pure "syntactic sugar" only then, not add details. Tx, fine; let's close?
