### ISSUE TITLE
Assertion methods taking a predicate

### ISSUE THREAD

**Issue by PhilippWendler** [google/truth#311]
I repeatedly have the case that I want to write an assertion about a specific method returning `true` (or `false`) for a given object. Currently I use `assertThat(foo.isBar()).isTrue()`, which does not give helpful failure messages.

I could solve this with a specific subject for the class of `foo`, but often I have just a few tests that call `isBar`, and the effort for writing a subject is not worth it. (I typically consider writing a `FooSubject` only in cases where I want to use `Foo`s in tests of other classes, not only in tests of `Foo` itself). In other cases, the method I want to test is not directly related to the class of `foo`, and adding a case for it in `FooSubject` would be awkward.

So I propose to add two methods to `Subject` that take a `Predicate` and could be used as follows:
```
assertThat(foo).satisfies(Foo::isBar);
assertThat(foo).doesNotSatisfy(Foo::isBar);
```
I think this is relatively nice to read and can give helpful error messages (I wonder whether the `toString` result of lambdas and method references is somewhat useful?). The methods could have different names, of course.

If the Java 8 dependency is a problem, maybe Guava's predicate could be used?

Alternatively, we could approach this the other way and add something like this:
```
assertThat(Foo::isBar).returnsTrueFor(foo);
```
I think the former to be more natural and more in line with Truth's existing methods, but the latter would emphasize that we test `isBar` here.

If this is added, maybe consider also something for a `Predicate` and an `Iterable`? However, my main use case are for the single-object case.

What do you think about this? Both approaches would be fine for me.

**Comment by kevinb9n** [comment]
> (I wonder whether the toString result of lambdas and method references is somewhat useful?)

It is the opposite of useful, and that's part of what has killed this idea for Truth, because Truth is all *about* useful messages.

> Alternatively, we could approach this the other way and add something like this.... I think the former to be more natural and more in line with Truth's existing methods, but the latter would emphasize that we test isBar here.

Yes, the latter is against the Truth design ethos. The conventional recipe for a unit test looks like "arrange, act, assert"; Truth's goal is to support the third part, not conflate multiple parts together.

**Comment by PhilippWendler** [comment]
I understand. Does this mean that this proposal won't be accepted?
The error message of `assertThat(foo).satisfies(Foo::isBar);` would at least still be better than the one of `assertThat(foo.isBar()).isTrue();` because of `foo.toString()`.

**Comment by dimo414** [comment]
I think the general solution to that problem is to use `assertWithMessage()`, which lets you either just pass in `foo` or (if it's helpful) extract something more meaningful from `foo` to display.

**Comment by dimo414** [comment]
Or, depending on the specifics, it might make sense to define your own `FooSubject` so you could write `assertThat(foo).isBar()`. Then you can have any error message you'd like.

**Comment by cpovirk** [comment]
I'm going to close this along with https://github.com/google/truth/issues/206 and https://github.com/google/truth/issues/435. All these proposals could be useful in some cases, but we've largely committed to `assertWithMessage` and `FooSubject` (and the other approaches mentioned in the other bugs) for them, as @dimo414 says. If we start trying to cover multiple "paradigms" for custom assertions, I worry that we won't do them all well and that users will be confronted with more options than they know what to do with.
