### ISSUE TITLE
Document Truth's beta status and describe the library's release philosophy

### ISSUE THREAD

**Issue by dimo414** [google/truth#316]
Truth should mention somewhere that it's still in Beta (hence the [0. version number](http://semver.org/#spec-item-4)), and describe what that means for users, similar to what [Guava does](https://github.com/google/guava/wiki/PhilosophyExplained#iteration).

**Comment by cpovirk** [comment]
And we haven't done this :(

With the 1.0 release imminent, is there anything we should say here? If so, maybe it could go in https://truth.dev/faq? Or maybe we wait for someone to ask, if it doesn't become obvious by version 1.46 or so?

**Comment by dimo414** [comment]
It'd be good to document somewhere the "big" changes from pre-1.0 Truth (as in, before the versions that were precursors to 1.0, like removing `Subject`'s generics) and catalog the migration path.

**Comment by cpovirk** [comment]
On that front, at least, I have tried to be pretty thorough in [the release notes](https://github.com/google/truth/releases).

I guess that the 1.0 release notes will be at least one good place to mention API stability.

**Comment by cpovirk** [comment]
I'm mentioning binary compatibility in [the release notes](https://github.com/google/truth/releases/tag/release_1_0) (not yet published, so GitHub is just showing a recent commit description, but eventually that link will work). I'm also linking back to the release notes for the release candidates.

That's probably good enough for now, but we can always add more if people have questions.
