### ISSUE TITLE
Subject.isEqualTo() doesn't work with arrays

### ISSUE THREAD

**Issue by gortiz** [google/truth#335]
Subject#isEqualTo javadoc says it doesn't fail if both values are arrays and considered equal by the appropriate Arrays#equals overload, but it is not true.

It seems to be an error between static and dynamic types. Truth#assertThat(byte[]), for example, returns a PrimitiveByteArraySubject, which works as intended. But Truth#assertThat(object) returns a Subject. Subject#isEqualTo delegates into Subject#doEqualCheck, which has an special case when values are integral boxes but treats arrays as normal objects, so at the end it uses Object#equals to test for equality.

I have forked the repository to add a test that verifies it ([link](https://github.com/gortiz/truth/commit/5c3f04562cd5e6acd33953877d9d8a40ac3a43e3)). If you are interested in, I can create a PR

**Comment by dimo414** [comment]
I notice the integral boxed types check was added in 152ee4e2dd, which also added the "they are arrays and are considered equal by the appropriate {@link Arrays#equals} overload" statement to the docs, but I don't see any unit tests in that commit related to array handling.

**Comment by cpovirk** [comment]
I do think we intended to do this but lost sight of it because most of the discussion was over the integral types. I'd be happy to look at a PR.
