### ISSUE TITLE
Support "fail" API similar to AssertJ

### ISSUE THREAD

**Issue by jaredsburrows** [google/truth#351]
http://joel-costigliola.github.io/assertj/core/api/org/assertj/core/api/Fail.html

**Comment by jaredsburrows** [comment]
It looks like the tests still use Junit's `fail`: https://github.com/google/truth/blob/beb77eecea5c528dd59797ba15baeebb5d7eb461/core/src/test/java/com/google/common/truth/CustomFailureMessageTest.java#L41.

**Comment by cpovirk** [comment]
If I'm understanding right, we do have this:

`assert_().fail("Should have thrown")`

https://google.github.io/truth/api/latest/com/google/common/truth/StandardSubjectBuilder.html#fail-java.lang.String-java.lang.Object...-

Probably some doc or other should be changed to mention it, though.

(We could also use it in our tests if we wanted. The current `fail` seems OK (and concise), so we might never bother.)

**Comment by cpovirk** [comment]
...not that we support an exception/cause, though, and not that we provide methods like `failBecauseExceptionWasNotThrown` (for which we'd probably just recommend the JUnit `assertThrows`). Maybe we should consider the exception one. Certainly I've written `failWithCause` helpers on a number of occasions.

Are there other parts we should consider.

**Comment by jaredsburrows** [comment]
@cpovirk Thanks. I did not see that. This will do.
