### ISSUE TITLE
Error building project on IntelliJ - Duplicate class com.google.common.truth.Platform

### ISSUE THREAD

**Issue by ragunathjawahar** [google/truth#354]
````
Information:java: Errors occurred while compiling module 'truth'
Information:javac 1.8.0_144 was used to compile java sources
Information:17/9/17 9:54 AM - Compilation completed with 1 error and 9 warnings in 2s 326ms
/home/user/IntelliJProjects/truth/core/src/main/java/com/google/common/truth/super/com/google/common/truth/Platform.java
Error:(31, 7) java: duplicate class: com.google.common.truth.Platform
````

**Comment by dimo414** [comment]
Yep, there are two `Platform` implementations, one [for the JVM](https://github.com/google/truth/blob/master/core/src/main/java/com/google/common/truth/Platform.java), and [one for GWT](https://github.com/google/truth/blob/master/core/src/main/java/com/google/common/truth/super/com/google/common/truth/Platform.java). If you aren't using GWT you don't need to care about the latter, and can just remove `core/src/main/java/com/google/common/truth/super` from your build paths.

**Comment by ragunathjawahar** [comment]
Yes, I did. I tried importing the parent project from the root `pom.xml` as well as tried to import the core project from the `core/pom.xml`. It doesn't make a difference.

**Comment by dimo414** [comment]
It sounds like an IntelliJ bug, then. The project [builds successfully](https://travis-ci.org/google/truth) off that `pom.xml` in CI. You ought to be able to manually exclude the `super` directory from your project if you can't get IntelliJ to parse it properly.
