### ISSUE TITLE
Introduce MapSubject#containsEntries(<var args with keys and values>)

### ISSUE THREAD

**Issue by skingsland** [google/truth#401]
I'd like to assert that a Map contains certain entries. I can do this easily with separate `containsEntry` calls:

        assertThat(myMap).containsEntry("name", "Steve");
        assertThat(myMap).containsEntry("email", "foo@bar.com");
        assertThat(myMap).containsEntry("active", true);

Would it make sense to introduce a `containsEntries` method to `MapSubject`, to assert multiple entries at once?

        assertThat(myMap).containsEntries("name", "Steve", 
                                          "email", "foo@bar.com", 
                                          "active", true);

**Comment by cpovirk** [comment]
I'm surprised that I don't remember hearing this requested before. Thanks for raising it.

We have a varargs [`containsExactly`](https://google.github.io/truth/api/latest/com/google/common/truth/MapSubject.html#containsExactly-java.lang.Object-java.lang.Object-java.lang.Object...-) for cases in which you know _all_ the entries that should be present.

But for cases in which you know only _some_ entries, the best we currently have is multiple `containsEntry` calls.

If we were to add this, we might want to add the full family of `IterableSubject`-like methods:

- `containsAllOf` (the one you want, which we might someday rename on `IterableSubject` to `containsAtLeast`)
- `containsAnyOf`
- `containsNoneOf` (which we've considered renaming to `doesNotContainAnyOf`)

I did a quick search of the Google codebase for multiple consecutive `containsEntry` calls. I didn't narrow them down to specifically `MapSubject` calls, so my numbers are surely wrong. But it looks like the number of consecutive `containsEntry` calls very roughly 10% of the number of `MapSubject.containsExactly` calls. Now some of those callers could be using `containsExactly`, and either they didn't realize it, or it didn't exist yet (as it didn't for the first ~1/3 of Truth's life at Google).

That's possibly worth doing, especially if it provides other features that are harder to emulate (e.g., `containsAnyIn` requires something like `union(a.entrySet(), b.entrySet())`. On the downside, it means you may want to manually pair up your args on each line (and I <3 [autoformatters](https://github.com/google/google-java-format)). But it also means that you don't need to repeat `myMap` (or extract it to a variable) if it's a longer expression. And you get more information in your error message (though you could also use `Expect` to accumulate errors, but even that would produce spammy output).

This deserves some more thought and research that I don't expect to carve out in the near future, but we should keep this in mind, probably for right after we figure out whether to rename any of the corresponding `IterableSubject` methods.

**Comment by skingsland** [comment]
Thanks for your quick and thorough response, @cpovirk! You are correct that this is needed when I only want to verify a _subset_ of the entries in the Map.

I don't think this is a _hugely_ beneficial feature, but as you pointed out it would provide a few minor benefits; to summarize:

1. less code to read;
1. don't need to repeat the map variable or expression;
1. the failure message includes _all_ missing entries, not just the first one that's missing;
1. others?

> If we were to add this, we might want to add the full family of IterableSubject-like methods:

That would be great, I was a bit surprised to see that they don't exist!

> This deserves some more thought and research that I don't expect to carve out in the near future, but we should keep this in mind, probably for right after we figure out whether to rename any of the corresponding IterableSubject methods.

OK great, so I should follow this issue then? Let me know if I can be of further assistance with moving this along!

**Comment by cpovirk** [comment]
Yep, you can follow along here.

**Comment by malcolmr** [comment]
fwiw, I wanted to have `assertThat(map).containsAllIn(subsetMap)` today to verify that a given map contained all the mappings from another (plus maybe some other ones).

(Instead I'm doing `for (Map.Entry<K, V> e : subsetMap.entrySet()) assertThat(map).containsEntry(e.getKey(), e.getValue());`, which works, but is more verbose, and won't give as good an error message.)

**Comment by cpovirk** [comment]
Sorry, I forgot to update this when [Truth 0.43](https://github.com/google/truth/releases/tag/release_0_43) added `containsAtLeast` and `containsAtLeastEntriesIn`.
