### ISSUE TITLE
Roll the 1.0 release

### ISSUE THREAD

**Issue by cgruber** [google/truth#41]
This should be the last step in the 1.0 milestone.  Ship it!

**Comment by swankjesse** [comment]
Lol.

**Comment by cgruber** [comment]
Yeah. Don't even start. :(

At this point, @cpovirk is working out the extension APIs a bit, and once we stabilize those, we're 1.0-ing that, but yeah - this is pretty ridiculous.

**Comment by mfarrugi** [comment]
At this point should users be wary of breaking changes in any (particular subset) of the vanilla apis?

**Comment by cpovirk** [comment]
> At this point should users be wary of breaking changes in any (particular subset) of the vanilla apis?

The things we're most actively working on right now are the APIs that people use when implementing custom `Subject` subclasses. In particular:

- We're replacing all the `fail*` methods with a new API.
- We might eliminate the type parameters on `Subject`, the `named()` method, and the `actual()` accessor. (But this needs more thought.)
- We might tweak other things, like replacing `actualCustomStringRepresentation()` with `formatActualOrExpected(Object)`. (This, too, needs more thought.)

I gather that you're asking more about the built-in assertions themselves, though? The only likely changes I can think of offhand are:

- `IterableSubject.containsAll*` -> `containsAtLeast*`
- `Subject.isSameAs` -> `isSameInstanceAs`
- `ClassSubject.isAssignableTo` -> `isSubtypeOf`

I might be forgetting some, but I don't expect a ton of changes.

I do want to get things stabilized more, but my time focusing on Truth is running short, so it may still be a while, unfortunately.

**Comment by cpovirk** [comment]
Announcement coming shortly.

**Comment by cpovirk** [comment]
https://opensource.googleblog.com/2019/07/truth-10-fluent-assertions-for-java-and.html

**Comment by cgruber** [comment]
\o/ !!!!!!!!!!
