### ISSUE TITLE
Add noneMatch and allMatch methods to StreamSubject

### ISSUE THREAD

**Issue by aeneid** [google/truth#435]
It seems to me that having these two methods would allow for a very natural and fluent way of checking for the existence of elements that match a certain predicate. 
The way one would approach this now is to perform the operation inside assertThat() and then invoke isTrue() or isFalse() which is somewhat cumbersome if you ask me.
If this is something you think is useful I can provide a PR.

**Comment by cpovirk** [comment]
There are some similarities here to https://github.com/google/truth/issues/206, so you may want to look at https://github.com/google/truth/issues/206#issuecomment-145528178 if you haven't already. We've contemplated some other ways of providing this functionality but don't have any plans yet. For `allMatch` and `noneMatch`, in particular, you might use [`Expect`](https://google.github.io/truth/api/latest/com/google/common/truth/Expect.html) to assert about each element individually.

**Comment by cpovirk** [comment]
As I just commented in #206, I don't think we're going to add these `Predicate`-oriented methods. `Expect` is probably the right tool here.

**Comment by volo-droid** [comment]
@cpovirk Can you please provide an example of an idiomatic way of asserting that all iterable items have an expected `id`?
```kotlin
data class Item(val id: String)

val items: Iterable<Item> = listOf(
    Item("id1"), Item("id2"), Item("id1"), 
)

val expectedId = "id1"

assertThat(items). … // ???
```
