### ISSUE TITLE
MapSubject.containsEntriesIn(Map<?,?>)

### ISSUE THREAD

**Issue by PhilippWendler** [google/truth#465]
I would like to propose adding `MapSubject.containsEntriesIn(Map<?,?>)`.

Currently, there is only `containsExactlyEntriesIn`, but while the latter is easy to implement using the former, it is currently not easy to replace `containsEntriesIn` with something else (one would need to use `IterableSubject.containsAllIn` on the entry sets).

The use case is for methods that are expected to add new entries to an existing map, where the test should assert that the previous entries are still present. I would expect this to be common.

This is a little bit similar to https://github.com/google/truth/issues/401#issuecomment-359054980, but that issue is about varargs methods, and that wouldn't help for my use case.

**Comment by cpovirk** [comment]
Sorry, I forgot to update this when [Truth 0.43](https://github.com/google/truth/releases/tag/release_0_43) added `containsAtLeast` and `containsAtLeastEntriesIn`.
