### ISSUE TITLE
Duplicate classes in Truth 0.41

### ISSUE THREAD

**Issue by madisp** [google/truth#467]
Truth pulls in both `org.checkerframework:checker-compat-qual` and `org.checkerframework:checker-qual`.

Both artifacts contain some classes, like `org.checkerframework.checker.formatter.FormatUtil` - typetools/checker-framework#712

This breaks Android builds :/ Workaround is to go back to 0.40

**Comment by cpovirk** [comment]
Truth fix released in [Truth 0.42](https://github.com/google/truth/releases/tag/release_0_42)... but we may need a Guava release (possibly coming on Wednesday?) and then an update for Truth to use _that_ for the problem to fully go away.
