### ISSUE TITLE
assertWithMessage does not support java8

### ISSUE THREAD

**Issue by brandonpollack23** [google/truth#469]
I have to convert these to look like
assertWithMessage(message).that(condition).isEqualTo(Optional.empty);

but I should be able to say
assertWithMessage(message).that(condition).isEmpty()

**Comment by jrtom** [comment]
There is an extension that I believe does what you want: https://github.com/google/truth/tree/master/extensions/java8/src/main/java/com/google/common/truth

**Comment by cpovirk** [comment]
`assertWithMessage(message).about(optionals()).that(condition).isEmpty()`

...which of course is about as long as the workaround....

It would be nice for us to document this in http://google.github.io/truth/faq#java8

We cover the general case in http://google.github.io/truth/faq#full-chain

This is definitely not an ideal situation, but we didn't have any great alternatives. Hopefully someday soonish we'll be able to add `Optional` support to core Truth, at which point your desired code will work.

**Comment by jrtom** [comment]
also: https://google.github.io/truth/faq#java8

**Comment by brandonpollack23** [comment]
Thanks for the swift replies, fellas. 

Yeah adding an extension/dependency isn't really ideal in my work scenario, but it is duly noted in personal projects :)

**Comment by cpovirk** [comment]
If `[Truth8.]assertThat(message).isEmpty()` already works for an `Optional`, then you're already using the extension. But if not, then yeah, new dependency necessary.

**Comment by cpovirk** [comment]
I've made changes to cover this more explicitly in both the `Truth8` docs and the FAQ (though the latter hasn't been mirrored out yet). It's still an unfortunate scenario, and hopefully someday we can get the Java 8 types into the main `Truth` class.
