### ISSUE TITLE
checker-compat-qual removed from Checker Framework 2.5.6

### ISSUE THREAD

**Issue by wltjr** [google/truth#497]
Starting with Checker Framework 2.5.6 they have removed the [checker-compat-qual artifact](https://github.com/typetools/checker-framework/releases). Seems like its mostly just one annotation, ```org.checkerframework.checker.nullness.compatqual.NullableDecl``` used in many places.  Possible replacement ```org.checkerframework.checker.nullness.qual.Nullable``` in checker-qual. In Checker Framework 2.5.6 there is no longer a ```NullableDecl``` or any of the classes that resided in ```org.checkerframework.checker.nullness.compatqual```.

**Comment by sdavids** [comment]
Related to https://github.com/google/guava/issues/2960

**Comment by olekw** [comment]
@meteorcloudy: Just pushed the Checker Framework fix here. I'll do the same in Flogger. Any other projects that still need this? Those are the only two I remember patching in Debian.

**Comment by meteorcloudy** [comment]
@olekw Thanks! I don't remember there are other projects needed to patch.

**Comment by cpovirk** [comment]
The dependency change has been released in [Truth 1.1](https://github.com/google/truth/releases/tag/release_1_1).
