### ISSUE TITLE
Add check for sublists

### ISSUE THREAD

**Issue by vRallev** [google/truth#533]
There is currently no way to check if a list contains a sublist. This feels like one of the more common checks to me that would fit nicely into Truth. The closest that I came up with is:
```kotlin
    assertThat(listOf("a", "b", "d", "c"))
        .containsAllOf("b", "c")
        .inOrder()
```
But there isn't a way to check if the items occur consecutively.

**Comment by cgruber** [comment]
To clarify, you mean a strict sublist, as in ["b", "d"] would be a sublist, but ["b", "c"] would not, right?

**Comment by vRallev** [comment]
Yes, correct.

**Comment by cpovirk** [comment]
We had a request for this a while back -- possibly from the Bazel team, as we tried to find potential users, and Bazel was almost the only place we could find them :(

I just gave it a shot again with queries like:
- `indexOfSubList` (the method on `Collections` that at least handles the logic for you)
- `containssublist` (on the theory that people would name methods that)
- `subList[(][a-rt-z].*equals|equals.*subList[(][a-rt-z]`

Based on that, I don't think this would see widespread enough usage, especially given that our `contains*` offerings are already a bit intimidatingly large. But if you have other ideas for how to search for users, let me know.

**Comment by vRallev** [comment]
That's fair. We only had 2-3 use cases, which probably could have been solved with `indexOfSubList`. Feel free to close the issue.

**Comment by cpovirk** [comment]
For my reference: The internal feature request is "Re-introduce containsSequence in IterableSubject."

**Comment by cpovirk** [comment]
Closing, but I'm sure we'll hear about this again, and we can reevaluate if we find some patterns where it's a clear win.
