### ISSUE TITLE
ability to negate assertions

### ISSUE THREAD

**Issue by david-gang** [google/truth#545]
This request is a continuation of: https://stackoverflow.com/a/55690555/2343743
When using the library it is just possible to use positive assertions.
assertThat(myString).contains("aaa")
assertThat(myString).doesNotContain("aaa")

so this means that for every assertion you have to write two assertions. one positive and one negative assertions.

Would it be possible just yo have a not operator?

assertTham(myString).not().contains("aaa")

In some cases not all negations will be present and i want to have these negations without asking for a PR.

**Comment by kluever** [comment]
Yes it is a bit more work for `Subject` authors to write 2 assertions, but it makes the user-written assertions more fluent, and also improves error messages.
