### ISSUE TITLE
Delete ListMultimapSubject and SetMultimapSubject?

### ISSUE THREAD

**Issue by cpovirk** [google/truth#555]
Originally `ListMultimapSubject` had a `valuesForKey` method that returned a `ListSubject`. Now there's no `ListSubject`, only `IterableSubject`, so the type exists only to deprecate `isEqualTo(SetMultimap)`. Then again, to be fair, we added `SetMultimapSubject` for _only_ that reason (or maybe because it seemed weird to have one for `ListMultimap` but not `SetMultimap`?). But we haven't seen this as a good enough reason to add `ListSubject` and `SetSubject` (well, to keep `ListSubject` around), so I don't know why we'd see this as different. Handling type mismatches may be better handled by static analysis (and, as a backup, failure messages).

I see mention of `ListMultimapSubject` and `SetMultimapSubject` in a "Truth MultimapSubject" brainstorming doc, but I don't see much discussion, nor do I see them in the eventual API Review doc. We should think about this.

**Comment by kluever** [comment]
That sounds reasonable.

**Comment by cpovirk** [comment]
I was going to add that we didn't put a `ListMultimapWithProtoValuesSubject` and `SetMultimapWithProtoValuesSubject` in ProtoTruth -- but in fact we did :)

**Comment by cpovirk** [comment]
(Apparently we never did an `isEqualTo(Set)` overload for the old `ListSubject`.)
