### ISSUE TITLE
Primitive array subject `Iterable` views' methods are misnamed

### ISSUE THREAD

**Issue by cpovirk** [google/truth#570]
We have:

- `containsAtLeast`
- `containsAnyOf`
- `containsExactly`
- `containsNoneOf`

But the methods accept arrays, so they should use the names we use for `Iterable`- and array-accepting methods elsewhere:

- `containsAtLeastElementsIn`
- `containsAnyIn`
- `containsExactlyElementsIn`
- `containsNoneIn`

(To be clear, I'm talking about the methods in `PrimitiveDoubleArraySubject.DoubleArrayAsIterable` and `PrimitiveFloatArraySubject.FloatArrayAsIterable`.)

I didn't see explicit discussion of the names in the doc "Truth about arrays (esp. double[])," and in fact the doc suggests that we didn't yet have a precedent for array-accepting methods, as it links to bug 18153623, the bug about `IterableSubject.containsExactlyElementsIn(Object[])`, etc. Or really, we did have a precedent, and that was to tell people to call the varargs methods, like `containsExactly`. So we followed precedent fine; we just didn't realize that we had to update these methods when we added the methods to `IterableSubject`.

All that said, I can't imagine that I'll get around to fixing this, and I can live with that. Still, @kluever and @PeteGillin in case they want to argue that this is worse than I think. And I'm adding it to the 1.0 milestone to make sure I drop it _consciously_ when the time comes.

**Comment by cpovirk** [comment]
(If we really wanted, we could add the new names and keep the old. But I would feel bad deprecating them, since that will mean that lots of people write one thing and then "need" to switch to the other. And I'd feel bad _not_ deprecating them, since then users may be confused as to whether they differ.)

**Comment by cpovirk** [comment]
No one seems to overly mind this, so I'll close it. If anyone still wants to object, it _might_ not be too late.

**Comment by jbduncan** [comment]
I realise I'm a bit late, but have you considered keeping a "2.0 Breaking Changes" list somewhere to keep track of breaking changes that may be desirable for a potential Truth 2.0? :)

**Comment by jbduncan** [comment]
@cpovirk ^

**Comment by cpovirk** [comment]
Since I don't expect us to make breaking changes, I want to be careful about the message I'd send by having such a list. That said... I do have one :) -- but more with the idea that it could make some interesting blog posts for people interested in API Design or writing Truth for MyLanguage. I'm not sure anything will ever come of that, but we'll see.
