### ISSUE TITLE
Dependency convergence errors

### ISSUE THREAD

**Issue by pzygielo** [google/truth#589]
Dependency convergence errors while using `com.google.truth`:`truth`:`0.45`.

### Expected Behavior
* [Dependency Convergence](https://maven.apache.org/enforcer/enforcer-rules/dependencyConvergence.html) to pass for project using `com.google.truth`:`truth`.

### Actual Behavior
Build of project with dependency to `com.google.truth`:`truth` fails with violations like
```
Dependency convergence error for com.google.errorprone:error_prone_annotations:2.2.0 paths to dependency are:
+-X:Y:6-SNAPSHOT
  +-com.google.truth:truth:0.45
    +-com.google.guava:guava:27.0.1-android
      +-com.google.errorprone:error_prone_annotations:2.2.0
and
+-X:Y:6-SNAPSHOT
  +-com.google.truth:truth:0.45
    +-com.google.errorprone:error_prone_annotations:2.3.1
```
and
```
Dependency convergence error for org.checkerframework:checker-compat-qual:2.5.2 paths to dependency are:
+-X:Y:6-SNAPSHOT
  +-com.google.truth:truth:0.45
    +-com.google.guava:guava:27.0.1-android
      +-org.checkerframework:checker-compat-qual:2.5.2
and
+-X:Y:6-SNAPSHOT
  +-com.google.truth:truth:0.45
    +-org.checkerframework:checker-compat-qual:2.5.5
```

**Comment by cpovirk** [comment]
We have generally found `dependencyConvergence` to not help with avoiding diamond-dependency problems as much as we'd hoped. If you have any interest in setting up a [linkage monitor](https://github.com/GoogleCloudPlatform/cloud-opensource-java/issues?utf8=%E2%9C%93&q=%22linkage%22) or creating a dummy test project that depends on all the Truth artifacts and runs `requireUpperBoundDeps` against them, we'd be interested in results from that.
