### ISSUE TITLE
Unable to reproduce output mentioned in documentation

### ISSUE THREAD

**Issue by cowwoc** [google/truth#611]
I'm trying to reproduce the behavior mentioned in the documentation. https://truth.dev/ says that:

```
assertThat(projectsByTeam())
    .valuesForKey("corelibs")
    .containsExactly("guava", "dagger", "truth", "auto", "caliper");
```

should generate this output:

```
value of    : projectsByTeam().valuesForKey(corelibs)
missing (1) : truth
───
expected    : [guava, dagger, truth, auto, caliper]
but was     : [guava, auto, dagger, caliper]
multimap was: {corelibs=[guava, auto, dagger, caliper]}
  at com.google.common.truth.example.DemoTest.testTruth(DemoTest.java:71)
```

When I try to reproduce this locally I get:

```
value of    : multimap.valuesForKey(corelibs)
[...]
```

Is there a typo in the documentation? Should I be able to get `projectsByTeam()` in the output message?

**Comment by cpovirk** [comment]
Oops, I'm sorry about that. I never updated the "How to use Truth" docs to mention the secret sauce: You need to have ASM on the classpath. (We were conservative and made it an optional dependency.)

(There are other ways in which the "value of" line can fail to show up -- it's all best effort -- but the ASM dependency likely what you need. Let me know if you still aren't seeing it after that.)

**Comment by cowwoc** [comment]
Makes sense. Thank you.
