### ISSUE TITLE
Kotlin support for smart casting

### ISSUE THREAD

**Issue by changusmc** [google/truth#613]
```
    @Test
    fun testInstanceKTest() {
        val list: List<Int> = arrayListOf()
        
        kotlin.test.assertTrue(list is ArrayList<Int>)
        val arrayList2: ArrayList<Int> = list
    }
    

    @Test
    fun testInstanceTruth() {
        val list: List<Int> = arrayListOf()
        com.google.common.truth.Truth.assertThat(list is ArrayList<Int>)
        val arrayList1: ArrayList<Int> = list
    }
```

Kotlin offers smart casting, whereas Truth does not.

![Screenshot 2019-07-22 12 08 19](https://user-images.githubusercontent.com/8715059/61658092-69f20600-ac79-11e9-9778-00fa43d573e1.png)

**Comment by JakeWharton** [comment]
This is unlikely to happen for a multitude of reasons.

The primary one is that Truth is written in Java and is unlikely to change anytime soon, if ever.

Next, smartcasts in custom functions require contracts which is currently an unstable language feature of Kotlin. So if Truth were rewritten in Kotlin today, it could not leverage this feature yet.

Beyond that, contracts aren't currently supported for member functions. Your Truth example should actually be
```kotlin
assertThat(list).isInstanceOf(ArrayList::class.java)
```
where `isInstanceOf` is a member function on `ListSubject`. So the Kotlin contract design would have to be amended to support that, it would have to be implemented in the compiler, and go through stabalization.

And finally, contracts lack the ability to carry the subject over multiple methods calls so you have no way of associating the type check done in the call to `isInstanceOf(ArrayList::class.java)` with the subject passed to `assertThat(list)`.

**Comment by changusmc** [comment]
Thanks for the thoughtful explanation on why we likely won't see this feature.

What is your recommendation on writing a test case in `Truth` to downcast the type?

I've been using this and seems kind of boilerplate-y

```
@Test
fun testInstanceTruth() {
    val list: List<Int> = arrayListOf()
    assertThat(list).isInstanceOf(ArrayList::class.java)
    if (list is ArrayList) {
        val arrayList: ArrayList<Int> = list
    }
}
```

**Comment by JakeWharton** [comment]
I don't have a great answer. You can still do
```kotlin
assertTrue(list is ArrayList<*>)
```
or even just
```kotlin
assertNotNull(list as ArrayList<*>)
```
or just cast going into the `assertThat` method
```kotlin
assertThat(list as ArrayList<*>).contains(...)
```
