### ISSUE TITLE
`assertThat(boolean)` is harmful - violates fluent API principles

### ISSUE THREAD

**Issue by clehene** [google/truth#614]
This was raised before by @cpovirk https://github.com/google/truth/issues/48  and IMO the suggestion that error prone would catch it is irrelevant since truth doesn't require error prone.

Truth is a fluent API so the "contract" is that grammatically correct things would work as expected: "assert that something is true" is correct, yet Truth requires a double boolean check.

This looks natural:
```
assertThat(e.getStatus().getCode() == Status.ALREADY_EXISTS.getCode());

```
It's also consistent with how Guava preconditions work, however it's wrong and will always pass.

The correct (boolean) version is not fluent
```
assertThat(e.getStatus().getCode() == Status.ALREADY_EXISTS.getCode()).isTrue();

// and yes, it should be

assertThat(e.getStatus().getCode()).isEqualTo(Status.ALREADY_EXISTS.getCode());

```

Worse it's terribly difficult to spot and that's a sign of a bad API.

**Comment by kluever** [comment]
If you use https://github.com/google/error-prone , it will ensure that you "do something" with the result of `assertThat(...)` because it is annotated with `@CheckReturnValue`.

**Comment by jbduncan** [comment]
@clehene I'm not a Googler or on the Truth team, but I'm unclear on what you mean by `assertThat(e.getStatus().getCode()).isEqualTo(Status.ALREADY_EXISTS.getCode());` not being fluent. 

Would you mind clarifying? :thinking:

**Comment by jbduncan** [comment]
I agree with you that the first example is more natural, but IIUC, the reason why Truth (and AssertJ) adopt the less intuitive approach over the more natural one is because these assertion libraries have very limited access to code `e.getStatus().getCode() == Status.ALREADY_EXISTS.getCode()`, and thus they can't provide a more helpful message than `expected: <true> but was: <false>` (taken from JUnit 5's `assertTrue`).

Thus I _think_ you're asking for something that's very difficult to achieve in Java, but I could be wrong about this, and I'd love to be corrected. :)

**Comment by clehene** [comment]
@jbduncan that is fluent, the first one (`assertThat(e.getStatus().getCode() == Status.ALREADY_EXISTS.getCode()).isTrue()`) is not fluent. 
I was stating that normally it should be assert(something).isEqualsTo(expected) (which is fluent and works) rather than (`assert(a == b)`) but still ..

**Comment by jbduncan** [comment]
@clehene Oh oops, sorry, my mistake! Thanks for clarifying what you meant. :+1:

**Comment by jbduncan** [comment]
...for some reason I hadn't seen the `.isTrue()` at the end of your first example, so sorry for missing that!

**Comment by cpovirk** [comment]
This is quite possibly the biggest footgun in the Truth API. We once batted around some crazy ideas to try to catch it at runtime, but we couldn't find anything that seemed like an improvement. At this point, we're committed to the existing API. We might want to recommend Error Prone or similar static analysis somewhere prominent.
