### ISSUE TITLE
Introduce ComparableSubject.isNotEquivalentAccordingToCompareTo()

### ISSUE THREAD

**Issue by eljobe** [google/truth#615]
When I write tests for a new `Comparable` class, I am able to test almost all of the conditions that are interesting with the exception of two instances which are not equivalent according to `compareTo`.

For example:
```
Duration a = Duration.ofSeconds(5);
Duration b = Duration.ofSeconds(8);
assertThat(a.compareTo(b) == 0).isFalse();
```
I know I could:
```
assertThat(a).isLessThan(b);
```
or
```
assertThat(a).isAtMost(b);
```
But:
```
assertThat(a).isNotEquivalentAccordingToCompareTo(b);
```
is really expressing exactly what I intend to assert. Even if it isn't as fluent as `assertThat(a).isNotEquivalentTo(b);` would be.

**Comment by cpovirk** [comment]
We still need to write a doc to write about the subtle point that `isEquivalentAccordingToCompareTo` is _not_ intended for testing that `compareTo` is implemented properly (ditto for `isLessThan`, etc.). But in practice, we find that that is exactly how it's used much of the time.

That said, it's _unlikely_ that using it that way will cause a problem. (Contrast that with `isEqualTo`: Using it to test that `equals` is implemented properly _is_ likely to cause problems, as `isEqualTo` doesn't always call `equals`! This is discussed a little in https://github.com/google/truth/issues/268, but again, we haven't written a proper doc.)

That aside, it's possible that `isNotEquivalentAccordingToCompareTo` is a reasonable thing to have for some use cases, just as `isEquivalentAccordingToCompareTo` is exactly what some users need. (Which users? Here are a couple I know of: objects that implement `compareTo` but not `equals`, maybe sometimes for Joda-Time types (where I *think* `equals` and `compareTo` can differ?).)

What we recommend for testing `compareTo` implementations is `ComparatorTester`. It's available inside Google but not externally yet, so I don't know if that helps your current use case: https://github.com/google/guava/issues/2223

**Comment by perceptron8** [comment]
> (Which users? Here are a couple I know of: objects that implement compareTo but not equals, maybe sometimes for Joda-Time types (where I think equals and compareTo can differ?).)

@cpovirk Let's not forget about BigDecimal ;-)

**Comment by cpovirk** [comment]
> > (Which users? Here are a couple I know of: objects that implement compareTo but not equals, maybe sometimes for Joda-Time types (where I think equals and compareTo can differ?).)
> 
> @cpovirk Let's not forget about BigDecimal ;-)

True :) The kind of sad thing is that we have an explicit [`isEqualToIgnoringScale`](https://truth.dev/api/latest/com/google/common/truth/BigDecimalSubject.html#isEqualToIgnoringScale-java.math.BigDecimal-) family of methods on `BigDecimalSubject`, and those methods behave identically to `isEquivalentAccordingToCompareTo`, so `BigDecimal` users don't need `ComparableSubject.isEquivalentAccordingToCompareTo`. We'd realized that it might actually make more sense for `BigDecimalSubject` to _not_ extend `ComparableSubject`, instead declaring all its methods (`isLessThan`, etc.) itself but leaving out `isEquivalentAccordingToCompareTo` in favor of  `isEqualToIgnoringScale`, but that didn't feel worth the churn and possibly other confusion or problems. It almost makes we wish that we didn't have `isEqualToIgnoringScale` at all, but it's nice for its `String` and `long` overloads, which would be weird as overloads of `isEquivalentAccordingToCompareTo`, so... argh. We can't win :)

**Comment by eljobe** [comment]
Having now read #268, I regret having mentioned testing an implementation of `Comparable`. It isn't a good use case. Nor is it the only use case.

Imagine I have a class `NonequivalentValueGenerator<T>` with a `T nextValue()` method.

I'd like to test that the results from two calls to next don't return T's that are equivalent.

```java
NonequivalentValueGenerator<Duration> gen = new NonequivalentValueGenerator<>();
Duration a = gen.nextValue();
Duration b = gen.nextValue();
assertThat(a).isNotEquivalentAccordingToCompareTo(b);
```
is better than:
```java
NonequivalentValueGenerator<Duration> gen = new NonequivalentValueGenerator<>();
Duration a = gen.nextValue();
Duration b = gen.nextValue();
assertThat(a.compareTo(b) == 0).isFalse();
```

Right?

**Comment by cpovirk** [comment]
Yep, I'm with you on that.

The next thing to do here is figure out how often this comes up. I haven't had much luck with a search for:

`isEquivalentAccordingToCompareTo (compareTo[^{};]*isNotEqualTo[(]0[)]|compareTo[^{};]*==\s+0[)]\s*[.]isFalse|compareTo[^{};]*!=\s+0[)]\s*[.]isTrue) pcre:yes`

The few hits there look like tests of `compareTo`, so I tried searching for files that _don't_ mention `isEquivalentAccordingToCompareTo`:

-isEquivalentAccordingToCompareTo (compareTo[^{};]*isNotEqualTo[(]0[)]|compareTo[^{};]*==\s+0[)]\s*[.]isFalse|compareTo[^{};]*!=\s+0[)]\s*[.]isTrue) pcre:yes

Most hits there look like tests of `compareTo`, too, though I saw some using `ByteBuffer` (a case of a type that implements `compareTo` without `equals`).

**Comment by cpovirk** [comment]
@eljobe also turned up some possible hits with Hamcrest, which suggests a search along the lines of:

`compareTo[^{};]*\bnot[(]0[)] pcre:yes`

However, those turn out to be false positives, too :(

We're figuring that we'll abandon this, but if anyone has suggestions for other ways of establishing demand, let us know.
