### ISSUE TITLE
Expect's failure messages should include a stack trace

### ISSUE THREAD

**Issue by shicks** [google/truth#62]
When an ASSERT fails, it dumps a stack trace.  Expect is really nice because it allows lumping several closely-related tests together into a single test case, but if one fails it's difficult to see exactly which it was (see below).  Including a stack trace from the point of failure would make this much easier.  Has this been considered?

    java.lang.AssertionError: All failed expectations:
      1. Not true that "foo" is "bar"
      2. Expected IllegalArgumentException parsing "baz"
    
        at org.truth0.Expect.evaluate(Expect.java:74)
        at junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
        at junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)

It just goes on from there into the test runner, etc, not indicating any lines in my test case, since the error isn't thrown until the end of the test.

**Comment by kluever** [comment]
I think what you're looking for has been added:
`Expect.createAndEnableStackTrace();`
