### ISSUE TITLE
Provide asserWithMessage on in Java 8 extension

### ISSUE THREAD

**Issue by rimesc** [google/truth#628]
Truth 0.46 removed the `named` method from `Subject` in favour of `Truth.assertWithMessage`.  However, there is no corresponding `Truth8.assertWithMessage`, so there is no longer a way to set a custom message when asserting things about `Optional`s and `Stream`s.

**Comment by cpovirk** [comment]
We have some docs on how to do this [in the FAQ](https://truth.dev/faq#java8). I'll edit the release notes to mention this. Thanks for raising it. (And let me know if you know of other good places to document this -- maybe on `assertWithMessage` itself?)

**Comment by rimesc** [comment]
Thanks for the quick reply.  I didn't come across that in any of the docs that I read.

One quick thought: the FAQ doesn't make it clear where the static `optionals()` method is imported from and the individual `Subject` classes aren't the first place I'd think to look (although if you follow thelink to [the full fluent chain](https://truth.dev/faq#full-chain) you can infer it from the example there).

**Comment by cpovirk** [comment]
Thanks, fix for that coming shortly.
