### ISSUE TITLE
unclear error for list comparison

### ISSUE THREAD

**Issue by oshai** [google/truth#649]
I have a code like this:
```
ProtoTruth.assertThat(myList).reportingMismatchesOnly().ignoringRepeatedFieldOrder()
      .displayingDiffsPairedBy { it?.name }
      .containsExactly(obj1, obj2)
```
it is running with two objects:
```
//expected
id: 1 name: integration 1
id: 2 name: integration 2
//actual
id: 2 name: integration 1
id: 1 name: integration 2
```
It seems that `containsExactly` is ignoring `displayingDiffsPairedBy` or at least it doesn't looks like best effort match. or maybe the output is just not clear to me.

here is the simplified output:

```
Not true that <[id: 1 name: "integration 1", id: 2 name: "integration 2"]> 
contains exactly one element that is equivalent according to assertThat(proto).reportingMismatchesOnly().ignoringRepeatedFieldOrder().isEqualTo(target) to each element of <[id: 2 name: "integration 1", id: 2 name: "integration 2"]>. 
It is missing an element that corresponds to <id: 2 name: "integration 1"> 
and has unexpected elements <[id: 1 name: "integration 1" (diff: Differences were found: modified: id: 2 -> 1 )]> with key integration 1
```

**Comment by nglorioso** [comment]
I think that: `with key integration 1` at the end of the output is the result of your `displayingDiffsPairedBy`.

**Comment by cpovirk** [comment]
(The general issue stands that this message is a wall of text. We've started migrating the ProtoTruth message to the key-value format that most of our assertions use ([example](https://github.com/google/truth/blob/30e3c4336541f826a105bbaffab28b04582ed1f9/core/src/test/java/com/google/common/truth/IterableSubjectCorrespondenceTest.java#L140)), but it's a long process. Sorry for the mess in the meantime.)

**Comment by oshai** [comment]
Thanks!
