### ISSUE TITLE
Code Correctness: Erroneous String Compare

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [google/truth#650]
https://github.com/google/truth/blob/6fc8b9774d1e05c3b3b884fd43cbb30c808fbbee/core/src/main/java/com/google/common/truth/MultimapSubject.java#L522-L524
Strings should be compared with the equals() method, not == or !=.

**Comment by jbduncan** [comment]
@QiAnXinCodeSafe It looks like they are already. Am I missing something? 🤔
