### ISSUE TITLE
Consider Kotlin extension-method "overloads" to StandardSubjectBuilder.that

### ISSUE THREAD

**Issue by cpovirk** [google/truth#660]
Everywhere we expose a `Subject.Factory` (or `CustomSubjectBuilder.Factory`), we could expose a `that` method. Such methods would save users of `assertWithMessage`, `check`, `expect`, etc. (maybe including `ExpectFailure` in the `Subject`'s own tests :)) from having to call `about(foos())`.

**Comment by tuanchauict** [comment]
Hi,
(I'm not sure I fully understand this issue, but I feel my idea is close to this.)

When I try to create a new Subject (in Kotlin), I feel it's not straightforward. There are some questions prompted in my head like:
- What is `FailureMetadata`? how I can create that object? do I need to create that object?
- How can I create `assertThat`? where should I put my `assertThat` for my subject?
- With the [Employee sample ](https://github.com/google/truth/blob/master/core/src/test/java/com/google/common/truth/extension/EmployeeSubject.java#L38), do I need to care `employees()` if I just need to care `assertThat()`?
- etc.

I suggest a new way:

```kt
abstract class SubjectFactory<S : Subject, T>(
    subjectConstructor: (metadata: FailureMetadata, actual: T?) -> S
) {
    private val subjectFactory: Factory<S, T> = Factory<S, T>(subjectConstructor)

    protected fun withActual(actual: T?): S = assertAbout(subjectFactory).that(actual)

    abstract fun assertThat(actual: T?): S

    fun assertThat(actual: T?, assertions: S.() -> Unit) = assertThat(actual).run(assertions)
}
```
Then for a new subject, we just need:
```kt
class XyzSubject(
    metadata: FailureMetadata,
    private val actual: Xyz?
) : Subject(metadata, actual) {
    // Snippet

    companion object : SubjectFactory<XyzSubject, Xyz>(::XyzSubject) {
        override fun assertThat(actual: Xyz?): XyzSubject = withActual(actual)
    }
}
```

> Disclaim: today is the first day I try Truth but I love it

**Comment by cpovirk** [comment]
Thanks, @tuanchauict. I finally had a detailed look at your suggestion. I think it would be the best approach for someone who wants to use `XyzSubject` from Kotlin only. Inside Google, though, we're still usually interested in making our code usable from both Kotlin and Java. And to do that, we want to put `@JvmStatic` on the `Factory` accessor and `assertThat` method, as in [this example](https://github.com/google/truth/issues/661#issuecomment-1452472936). That [doesn't appear to be possible](https://pl.kotl.in/iUCf6_Jf4) with the `abstract class SubjecFactory` approach.

All that said, we know people who are looking more at pure Kotlin projects, so we may eventually want to provide exactly what you're suggesting for them.

**Comment by tuanchauict** [comment]
I hope Jetbrains will allow us to make `@JvmStatic` possible for the `companion object`. Here is a not-perfect workaround: https://pl.kotl.in/vcn1vZva9
