### ISSUE TITLE
Api pages break when searching

### ISSUE THREAD

**Issue by Cypher1** [google/truth#670]
Hitting the first result when searching 'isGreaterThan' in the api documentation leads to the following URL. Which returns a Github Pages page with a 404 error.

`https://truth.dev/api/latest/undefined/com/google/common/truth/DoubleSubject.html#isGreaterThan(int)`

Something is inserting an `undefined` in the path, the following URL works.

`https://truth.dev/api/latest/com/google/common/truth/DoubleSubject.html#isGreaterThan(int)`

**Comment by cpovirk** [comment]
Ugh -- thank you for reporting. Going to try [this](https://stackoverflow.com/a/52603413/28465).

**Comment by cpovirk** [comment]
Also, this is as good a chance as any to advertise my favorite recent addition to Truth (and Guava): We set up redirects for URLs like the following:

https://truth.dev/doublesubject

That will take you directly to (the correct location of :)) [`DoubleSubject`](https://truth.dev/api/latest/com/google/common/truth/DoubleSubject.html), which might even be marginally faster than Javadoc's built-in search (which, again, we should still fix).

**Comment by cpovirk** [comment]
That fix appears to work. (The warnings about breaking JDK links don't apply in our case. Details in internal CL 303110325, which will get mirrored out soon if all goes well.)

While I'm talking about short links: You can get to the Javadoc index with:
https://truth.dev/api

(Maybe you're aware of all this, but I can't miss the opportunity to plug it :))

**Comment by Cypher1** [comment]
Thanks!
