### ISSUE TITLE
Maven dependency conflict for error_prone_annotations with guava

### ISSUE THREAD

**Issue by kmehltretter** [google/truth#712]
truth:1.0.1 has a dependency to error_prone_annotations:2.3.3
truth:1.0.1 has a dependency to guava:28.1-android, which has a dependency to error_prone_annotations:2.3.2

Could these dependencies be "synchronized" to avoid a conflict ?

**Comment by cpovirk** [comment]
We should update Guava's version. (And, in the long term, we should have better automation for performing such updates automatically.)

To the best of my knowledge, given that Guava is behind in this case, it is still preferable for Truth to depend on a newer version of error_prone_annotations (as long as the upgrade doesn't change the a major version number; if it does, then things get complicated). If you're aware of cases in which it's better to stay with the older one, let me know.
