### ISSUE TITLE
Add Truth to cs.opensource.google

### ISSUE THREAD

**Issue by CydeWeys** [google/truth#769]
It'd be great if Truth were on https://cs.opensource.google/ (basically externally accessible Code Search) for easy codebase perusal and cross-referencing with other projects that use Truth.  Most of Google's most important open source projects are already on there including Abseil, Angular, Bazel, Copybara, Dart, Fuchsia, Go, Guava, TensorFlow, etc., so it'd be awesome to include Truth as well.  See http://go/osscs-onboarding for instructions.

**Comment by kluever** [comment]
SGTM

**Comment by CydeWeys** [comment]
Awesome, thanks.  Looks like we just need a logo then and we're good to go!

**Comment by hagbard** [comment]
Kurt, any chance you can do the same for Flogger?

**Comment by jianglai** [comment]
Do you plan to set up Kythe for cross referencing as well?

**Comment by kluever** [comment]
Fixed.
