### ISSUE TITLE
Truth has an issue when you use assertThat to check a length

### ISSUE THREAD

**Issue by wise4rmgod** [google/truth#788]
I tried to check the length of a word and it only works with number 5 only, the others give error no matter what
<img width="566" alt="Screenshot 2020-11-19 at 03 05 02" src="https://user-images.githubusercontent.com/22228278/99611680-65c42d00-2a14-11eb-8174-91467330a3e4.png">

<img width="1041" alt="Screenshot 2020-11-19 at 03 04 50" src="https://user-images.githubusercontent.com/22228278/99611716-74aadf80-2a14-11eb-81bd-7ebcd495d267.png">

<img width="1171" alt="Screenshot 2020-11-19 at 03 05 21" src="https://user-images.githubusercontent.com/22228278/99611687-68268700-2a14-11eb-8232-952d73195d02.png">

**Comment by netdpb** [comment]
It looks like the string returned by `Validate.checkLengthOfWord()` was "Error", which has five characters. (You can see that because Truth's failure message contains "string was: Error".

`Validate` isn't part of Truth, so you might want to check its documentation.
