### ISSUE TITLE
 Could not find com.google.truth.truth:1.1.2:.

### ISSUE THREAD

**Issue by Vishakha917** [google/truth#847]
I am new to testing. Trying unit testing, added dependencies for the same but still getting error Could not find com.google.truth.truth:1.1.2:. I tried searching for the solution all over. But no gain.

FULL ERROR:
`* What went wrong:
Execution failed for task ':app:processDebugAndroidTestManifest'.
> Could not resolve all files for configuration ':app:debugAndroidTestRuntimeClasspath'.
   > Could not find com.google.truth.truth:1.1.2:.
     Required by:
         project :app

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.`

DEPENDENCIES :
android {
    compileSdkVersion 30
    buildToolsVersion "30.0.3"

    defaultConfig {
        applicationId "com.example.android.unittestgithubpro"
        minSdkVersion 21
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {

    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation 'androidx.core:core-ktx:1.3.2'
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.material:material:1.3.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'

    //Tests
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
    testImplementation "com.google.truth:truth:1.1.2"
    androidTestImplementation "com.google.truth.truth:1.1.2"
    testImplementation "com.google.truth.extensions:truth-java8-extension:1.1.2"

}

**Comment by cpovirk** [comment]
This sounds like a network or configuration problem. I hope that someone is able to help you on https://stackoverflow.com/q/66966252/28465
