### ISSUE TITLE
New extension for Gradle's TestKit

### ISSUE THREAD

**Issue by autonomousapps** [google/truth#957]
https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/tree/main/testkit-truth, just published to maven central with coordinates `com.autonomousapps:testkit-truth:1.0`.

See [TestKit docs](https://docs.gradle.org/current/userguide/test_kit.html).

Not sure if there's a process for updating https://truth.dev/extension, but I thought it would be useful for others who might be looking to easily find this extension.

**Comment by kluever** [comment]
Thanks --- the list of extensions on that page isn't meant to be exhaustive. I suppose if it becomes really popular, we could consider adding it later though.
